// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// AddProjectUserPermissionReader is a Reader for the AddProjectUserPermission structure.
type AddProjectUserPermissionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddProjectUserPermissionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddProjectUserPermissionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAddProjectUserPermissionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAddProjectUserPermissionOK creates a AddProjectUserPermissionOK with default headers values
func NewAddProjectUserPermissionOK() *AddProjectUserPermissionOK {
	return &AddProjectUserPermissionOK{}
}

/*
AddProjectUserPermissionOK describes a response with status code 200, with default header values.

A successful response.
*/
type AddProjectUserPermissionOK struct {
	Payload interface{}
}

// IsSuccess returns true when this add project user permission o k response has a 2xx status code
func (o *AddProjectUserPermissionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add project user permission o k response has a 3xx status code
func (o *AddProjectUserPermissionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add project user permission o k response has a 4xx status code
func (o *AddProjectUserPermissionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add project user permission o k response has a 5xx status code
func (o *AddProjectUserPermissionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add project user permission o k response a status code equal to that given
func (o *AddProjectUserPermissionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the add project user permission o k response
func (o *AddProjectUserPermissionOK) Code() int {
	return 200
}

func (o *AddProjectUserPermissionOK) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/add-user-permission][%d] addProjectUserPermissionOK  %+v", 200, o.Payload)
}

func (o *AddProjectUserPermissionOK) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/add-user-permission][%d] addProjectUserPermissionOK  %+v", 200, o.Payload)
}

func (o *AddProjectUserPermissionOK) GetPayload() interface{} {
	return o.Payload
}

func (o *AddProjectUserPermissionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddProjectUserPermissionDefault creates a AddProjectUserPermissionDefault with default headers values
func NewAddProjectUserPermissionDefault(code int) *AddProjectUserPermissionDefault {
	return &AddProjectUserPermissionDefault{
		_statusCode: code,
	}
}

/*
AddProjectUserPermissionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type AddProjectUserPermissionDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this add project user permission default response has a 2xx status code
func (o *AddProjectUserPermissionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this add project user permission default response has a 3xx status code
func (o *AddProjectUserPermissionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this add project user permission default response has a 4xx status code
func (o *AddProjectUserPermissionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this add project user permission default response has a 5xx status code
func (o *AddProjectUserPermissionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this add project user permission default response a status code equal to that given
func (o *AddProjectUserPermissionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the add project user permission default response
func (o *AddProjectUserPermissionDefault) Code() int {
	return o._statusCode
}

func (o *AddProjectUserPermissionDefault) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/add-user-permission][%d] AddProjectUserPermission default  %+v", o._statusCode, o.Payload)
}

func (o *AddProjectUserPermissionDefault) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/add-user-permission][%d] AddProjectUserPermission default  %+v", o._statusCode, o.Payload)
}

func (o *AddProjectUserPermissionDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *AddProjectUserPermissionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
