// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: svc/compute/network/network_svc.proto

package network

import (
	securitygroup "github.com/CudoVentures/terraform-provider-cudo/internal/compute/securitygroup"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecurityGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecurityGroupRequest) Reset() {
	*x = GetSecurityGroupRequest{}
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecurityGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecurityGroupRequest) ProtoMessage() {}

func (x *GetSecurityGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecurityGroupRequest.ProtoReflect.Descriptor instead.
func (*GetSecurityGroupRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_svc_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecurityGroupRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetSecurityGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSecurityGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DataCenterId  string                 `protobuf:"bytes,2,opt,name=data_center_id,json=dataCenterId,proto3" json:"data_center_id,omitempty"`
	PageNumber    *int32                 `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3,oneof" json:"page_number,omitempty"`
	PageSize      *int32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecurityGroupsRequest) Reset() {
	*x = ListSecurityGroupsRequest{}
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecurityGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecurityGroupsRequest) ProtoMessage() {}

func (x *ListSecurityGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecurityGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListSecurityGroupsRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_svc_proto_rawDescGZIP(), []int{1}
}

func (x *ListSecurityGroupsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListSecurityGroupsRequest) GetDataCenterId() string {
	if x != nil {
		return x.DataCenterId
	}
	return ""
}

func (x *ListSecurityGroupsRequest) GetPageNumber() int32 {
	if x != nil && x.PageNumber != nil {
		return *x.PageNumber
	}
	return 0
}

func (x *ListSecurityGroupsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type ListSecurityGroupsResponse struct {
	state          protoimpl.MessageState         `protogen:"open.v1"`
	SecurityGroups []*securitygroup.SecurityGroup `protobuf:"bytes,1,rep,name=security_groups,json=securityGroups,proto3" json:"security_groups,omitempty"`
	TotalCount     int32                          `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PageNumber     int32                          `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize       int32                          `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListSecurityGroupsResponse) Reset() {
	*x = ListSecurityGroupsResponse{}
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecurityGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecurityGroupsResponse) ProtoMessage() {}

func (x *ListSecurityGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecurityGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListSecurityGroupsResponse) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_svc_proto_rawDescGZIP(), []int{2}
}

func (x *ListSecurityGroupsResponse) GetSecurityGroups() []*securitygroup.SecurityGroup {
	if x != nil {
		return x.SecurityGroups
	}
	return nil
}

func (x *ListSecurityGroupsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListSecurityGroupsResponse) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListSecurityGroupsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CreateNetworkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Create network params
	Network       *Network `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkRequest) Reset() {
	*x = CreateNetworkRequest{}
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkRequest) ProtoMessage() {}

func (x *CreateNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkRequest.ProtoReflect.Descriptor instead.
func (*CreateNetworkRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_svc_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNetworkRequest) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

type GetNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkRequest) Reset() {
	*x = GetNetworkRequest{}
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkRequest) ProtoMessage() {}

func (x *GetNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_svc_proto_rawDescGZIP(), []int{4}
}

func (x *GetNetworkRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PageNumber    *int32                 `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3,oneof" json:"page_number,omitempty"`
	PageSize      *int32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworksRequest) Reset() {
	*x = ListNetworksRequest{}
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworksRequest) ProtoMessage() {}

func (x *ListNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworksRequest.ProtoReflect.Descriptor instead.
func (*ListNetworksRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_svc_proto_rawDescGZIP(), []int{5}
}

func (x *ListNetworksRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListNetworksRequest) GetPageNumber() int32 {
	if x != nil && x.PageNumber != nil {
		return *x.PageNumber
	}
	return 0
}

func (x *ListNetworksRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type ListNetworksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []*Network             `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworksResponse) Reset() {
	*x = ListNetworksResponse{}
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworksResponse) ProtoMessage() {}

func (x *ListNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworksResponse.ProtoReflect.Descriptor instead.
func (*ListNetworksResponse) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_svc_proto_rawDescGZIP(), []int{6}
}

func (x *ListNetworksResponse) GetNetworks() []*Network {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *ListNetworksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListNetworksResponse) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListNetworksResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DeleteNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkRequest) Reset() {
	*x = DeleteNetworkRequest{}
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkRequest) ProtoMessage() {}

func (x *DeleteNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkRequest.ProtoReflect.Descriptor instead.
func (*DeleteNetworkRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_svc_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNetworkRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartNetworkRequest) Reset() {
	*x = StartNetworkRequest{}
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNetworkRequest) ProtoMessage() {}

func (x *StartNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartNetworkRequest.ProtoReflect.Descriptor instead.
func (*StartNetworkRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_svc_proto_rawDescGZIP(), []int{8}
}

func (x *StartNetworkRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *StartNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopNetworkRequest) Reset() {
	*x = StopNetworkRequest{}
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopNetworkRequest) ProtoMessage() {}

func (x *StopNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopNetworkRequest.ProtoReflect.Descriptor instead.
func (*StopNetworkRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_svc_proto_rawDescGZIP(), []int{9}
}

func (x *StopNetworkRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *StopNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateSecurityGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Create security group params
	SecurityGroup *securitygroup.SecurityGroup `protobuf:"bytes,1,opt,name=security_group,json=securityGroup,proto3" json:"security_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecurityGroupRequest) Reset() {
	*x = CreateSecurityGroupRequest{}
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecurityGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecurityGroupRequest) ProtoMessage() {}

func (x *CreateSecurityGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecurityGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateSecurityGroupRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_svc_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSecurityGroupRequest) GetSecurityGroup() *securitygroup.SecurityGroup {
	if x != nil {
		return x.SecurityGroup
	}
	return nil
}

type UpdateSecurityGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Update security group params
	SecurityGroup *securitygroup.SecurityGroup `protobuf:"bytes,1,opt,name=security_group,json=securityGroup,proto3" json:"security_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecurityGroupRequest) Reset() {
	*x = UpdateSecurityGroupRequest{}
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecurityGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecurityGroupRequest) ProtoMessage() {}

func (x *UpdateSecurityGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecurityGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecurityGroupRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_svc_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSecurityGroupRequest) GetSecurityGroup() *securitygroup.SecurityGroup {
	if x != nil {
		return x.SecurityGroup
	}
	return nil
}

type DeleteSecurityGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecurityGroupRequest) Reset() {
	*x = DeleteSecurityGroupRequest{}
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecurityGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecurityGroupRequest) ProtoMessage() {}

func (x *DeleteSecurityGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_svc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecurityGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecurityGroupRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_svc_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSecurityGroupRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteSecurityGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_svc_compute_network_network_svc_proto protoreflect.FileDescriptor

const file_svc_compute_network_network_svc_proto_rawDesc = "" +
	"\n" +
	"%svc/compute/network/network_svc.proto\x12\x13org.cudo.compute.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a!svc/compute/network/network.proto\x1a-svc/compute/securitygroup/securitygroup.proto\"R\n" +
	"\x17GetSecurityGroupRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\"\xcb\x01\n" +
	"\x19ListSecurityGroupsRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12$\n" +
	"\x0edata_center_id\x18\x02 \x01(\tR\fdataCenterId\x12$\n" +
	"\vpage_number\x18\x03 \x01(\x05H\x00R\n" +
	"pageNumber\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x04 \x01(\x05H\x01R\bpageSize\x88\x01\x01B\x0e\n" +
	"\f_page_numberB\f\n" +
	"\n" +
	"_page_size\"\xdc\x01\n" +
	"\x1aListSecurityGroupsResponse\x12P\n" +
	"\x0fsecurity_groups\x18\x01 \x03(\v2\".org.cudo.compute.v1.SecurityGroupB\x03\xe0A\x02R\x0esecurityGroups\x12$\n" +
	"\vtotal_count\x18\x02 \x01(\x05B\x03\xe0A\x02R\n" +
	"totalCount\x12$\n" +
	"\vpage_number\x18\x03 \x01(\x05B\x03\xe0A\x02R\n" +
	"pageNumber\x12 \n" +
	"\tpage_size\x18\x04 \x01(\x05B\x03\xe0A\x02R\bpageSize\"S\n" +
	"\x14CreateNetworkRequest\x12;\n" +
	"\anetwork\x18\x05 \x01(\v2\x1c.org.cudo.compute.v1.NetworkB\x03\xe0A\x01R\anetwork\"L\n" +
	"\x11GetNetworkRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\"\x9f\x01\n" +
	"\x13ListNetworksRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12$\n" +
	"\vpage_number\x18\x02 \x01(\x05H\x00R\n" +
	"pageNumber\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x03 \x01(\x05H\x01R\bpageSize\x88\x01\x01B\x0e\n" +
	"\f_page_numberB\f\n" +
	"\n" +
	"_page_size\"\xc3\x01\n" +
	"\x14ListNetworksResponse\x12=\n" +
	"\bnetworks\x18\x01 \x03(\v2\x1c.org.cudo.compute.v1.NetworkB\x03\xe0A\x02R\bnetworks\x12$\n" +
	"\vtotal_count\x18\x02 \x01(\x05B\x03\xe0A\x02R\n" +
	"totalCount\x12$\n" +
	"\vpage_number\x18\x03 \x01(\x05B\x03\xe0A\x02R\n" +
	"pageNumber\x12 \n" +
	"\tpage_size\x18\x04 \x01(\x05B\x03\xe0A\x02R\bpageSize\"O\n" +
	"\x14DeleteNetworkRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x03 \x01(\tB\x03\xe0A\x02R\x02id\"N\n" +
	"\x13StartNetworkRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x03 \x01(\tB\x03\xe0A\x02R\x02id\"M\n" +
	"\x12StopNetworkRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x03 \x01(\tB\x03\xe0A\x02R\x02id\"g\n" +
	"\x1aCreateSecurityGroupRequest\x12I\n" +
	"\x0esecurity_group\x18\x01 \x01(\v2\".org.cudo.compute.v1.SecurityGroupR\rsecurityGroup\"g\n" +
	"\x1aUpdateSecurityGroupRequest\x12I\n" +
	"\x0esecurity_group\x18\x01 \x01(\v2\".org.cudo.compute.v1.SecurityGroupR\rsecurityGroup\"U\n" +
	"\x1aDeleteSecurityGroupRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id2\xcc\r\n" +
	"\x0eNetworkService\x12\x95\x01\n" +
	"\rCreateNetwork\x12).org.cudo.compute.v1.CreateNetworkRequest\x1a\x1c.org.cudo.compute.v1.Network\";\x82\xd3\xe4\x93\x025:\anetwork\"*/v1/projects/{network.project_id}/networks\x12\x83\x01\n" +
	"\n" +
	"GetNetwork\x12&.org.cudo.compute.v1.GetNetworkRequest\x1a\x1c.org.cudo.compute.v1.Network\"/\x82\xd3\xe4\x93\x02)\x12'/v1/projects/{project_id}/networks/{id}\x12\x8f\x01\n" +
	"\fListNetworks\x12(.org.cudo.compute.v1.ListNetworksRequest\x1a).org.cudo.compute.v1.ListNetworksResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/projects/{project_id}/networks\x12\x83\x01\n" +
	"\rDeleteNetwork\x12).org.cudo.compute.v1.DeleteNetworkRequest\x1a\x16.google.protobuf.Empty\"/\x82\xd3\xe4\x93\x02)*'/v1/projects/{project_id}/networks/{id}\x12\x87\x01\n" +
	"\fStartNetwork\x12(.org.cudo.compute.v1.StartNetworkRequest\x1a\x16.google.protobuf.Empty\"5\x82\xd3\xe4\x93\x02/\"-/v1/projects/{project_id}/networks/{id}/start\x12\x84\x01\n" +
	"\vStopNetwork\x12'.org.cudo.compute.v1.StopNetworkRequest\x1a\x16.google.protobuf.Empty\"4\x82\xd3\xe4\x93\x02.\",/v1/projects/{project_id}/networks/{id}/stop\x12\xbc\x01\n" +
	"\x13CreateSecurityGroup\x12/.org.cudo.compute.v1.CreateSecurityGroupRequest\x1a\".org.cudo.compute.v1.SecurityGroup\"P\x82\xd3\xe4\x93\x02J:\x0esecurity_group\"8/v1/projects/{security_group.project_id}/security-groups\x12\x9c\x01\n" +
	"\x10GetSecurityGroup\x12,.org.cudo.compute.v1.GetSecurityGroupRequest\x1a\".org.cudo.compute.v1.SecurityGroup\"6\x82\xd3\xe4\x93\x020\x12./v1/projects/{project_id}/security-groups/{id}\x12\xa8\x01\n" +
	"\x12ListSecurityGroups\x12..org.cudo.compute.v1.ListSecurityGroupsRequest\x1a/.org.cudo.compute.v1.ListSecurityGroupsResponse\"1\x82\xd3\xe4\x93\x02+\x12)/v1/projects/{project_id}/security-groups\x12\xd0\x01\n" +
	"\x13UpdateSecurityGroup\x12/.org.cudo.compute.v1.UpdateSecurityGroupRequest\x1a\".org.cudo.compute.v1.SecurityGroup\"d\x82\xd3\xe4\x93\x02^:\x0esecurity_group2L/v1/projects/{security_group.project_id}/security-groups/{security_group.id}\x12\x96\x01\n" +
	"\x13DeleteSecurityGroup\x12/.org.cudo.compute.v1.DeleteSecurityGroupRequest\x1a\x16.google.protobuf.Empty\"6\x82\xd3\xe4\x93\x020*./v1/projects/{project_id}/security-groups/{id}BJZHgithub.com/CudoVentures/terraform-provider-cudo/internal/compute/networkb\x06proto3"

var (
	file_svc_compute_network_network_svc_proto_rawDescOnce sync.Once
	file_svc_compute_network_network_svc_proto_rawDescData []byte
)

func file_svc_compute_network_network_svc_proto_rawDescGZIP() []byte {
	file_svc_compute_network_network_svc_proto_rawDescOnce.Do(func() {
		file_svc_compute_network_network_svc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svc_compute_network_network_svc_proto_rawDesc), len(file_svc_compute_network_network_svc_proto_rawDesc)))
	})
	return file_svc_compute_network_network_svc_proto_rawDescData
}

var file_svc_compute_network_network_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_svc_compute_network_network_svc_proto_goTypes = []any{
	(*GetSecurityGroupRequest)(nil),     // 0: org.cudo.compute.v1.GetSecurityGroupRequest
	(*ListSecurityGroupsRequest)(nil),   // 1: org.cudo.compute.v1.ListSecurityGroupsRequest
	(*ListSecurityGroupsResponse)(nil),  // 2: org.cudo.compute.v1.ListSecurityGroupsResponse
	(*CreateNetworkRequest)(nil),        // 3: org.cudo.compute.v1.CreateNetworkRequest
	(*GetNetworkRequest)(nil),           // 4: org.cudo.compute.v1.GetNetworkRequest
	(*ListNetworksRequest)(nil),         // 5: org.cudo.compute.v1.ListNetworksRequest
	(*ListNetworksResponse)(nil),        // 6: org.cudo.compute.v1.ListNetworksResponse
	(*DeleteNetworkRequest)(nil),        // 7: org.cudo.compute.v1.DeleteNetworkRequest
	(*StartNetworkRequest)(nil),         // 8: org.cudo.compute.v1.StartNetworkRequest
	(*StopNetworkRequest)(nil),          // 9: org.cudo.compute.v1.StopNetworkRequest
	(*CreateSecurityGroupRequest)(nil),  // 10: org.cudo.compute.v1.CreateSecurityGroupRequest
	(*UpdateSecurityGroupRequest)(nil),  // 11: org.cudo.compute.v1.UpdateSecurityGroupRequest
	(*DeleteSecurityGroupRequest)(nil),  // 12: org.cudo.compute.v1.DeleteSecurityGroupRequest
	(*securitygroup.SecurityGroup)(nil), // 13: org.cudo.compute.v1.SecurityGroup
	(*Network)(nil),                     // 14: org.cudo.compute.v1.Network
	(*emptypb.Empty)(nil),               // 15: google.protobuf.Empty
}
var file_svc_compute_network_network_svc_proto_depIdxs = []int32{
	13, // 0: org.cudo.compute.v1.ListSecurityGroupsResponse.security_groups:type_name -> org.cudo.compute.v1.SecurityGroup
	14, // 1: org.cudo.compute.v1.CreateNetworkRequest.network:type_name -> org.cudo.compute.v1.Network
	14, // 2: org.cudo.compute.v1.ListNetworksResponse.networks:type_name -> org.cudo.compute.v1.Network
	13, // 3: org.cudo.compute.v1.CreateSecurityGroupRequest.security_group:type_name -> org.cudo.compute.v1.SecurityGroup
	13, // 4: org.cudo.compute.v1.UpdateSecurityGroupRequest.security_group:type_name -> org.cudo.compute.v1.SecurityGroup
	3,  // 5: org.cudo.compute.v1.NetworkService.CreateNetwork:input_type -> org.cudo.compute.v1.CreateNetworkRequest
	4,  // 6: org.cudo.compute.v1.NetworkService.GetNetwork:input_type -> org.cudo.compute.v1.GetNetworkRequest
	5,  // 7: org.cudo.compute.v1.NetworkService.ListNetworks:input_type -> org.cudo.compute.v1.ListNetworksRequest
	7,  // 8: org.cudo.compute.v1.NetworkService.DeleteNetwork:input_type -> org.cudo.compute.v1.DeleteNetworkRequest
	8,  // 9: org.cudo.compute.v1.NetworkService.StartNetwork:input_type -> org.cudo.compute.v1.StartNetworkRequest
	9,  // 10: org.cudo.compute.v1.NetworkService.StopNetwork:input_type -> org.cudo.compute.v1.StopNetworkRequest
	10, // 11: org.cudo.compute.v1.NetworkService.CreateSecurityGroup:input_type -> org.cudo.compute.v1.CreateSecurityGroupRequest
	0,  // 12: org.cudo.compute.v1.NetworkService.GetSecurityGroup:input_type -> org.cudo.compute.v1.GetSecurityGroupRequest
	1,  // 13: org.cudo.compute.v1.NetworkService.ListSecurityGroups:input_type -> org.cudo.compute.v1.ListSecurityGroupsRequest
	11, // 14: org.cudo.compute.v1.NetworkService.UpdateSecurityGroup:input_type -> org.cudo.compute.v1.UpdateSecurityGroupRequest
	12, // 15: org.cudo.compute.v1.NetworkService.DeleteSecurityGroup:input_type -> org.cudo.compute.v1.DeleteSecurityGroupRequest
	14, // 16: org.cudo.compute.v1.NetworkService.CreateNetwork:output_type -> org.cudo.compute.v1.Network
	14, // 17: org.cudo.compute.v1.NetworkService.GetNetwork:output_type -> org.cudo.compute.v1.Network
	6,  // 18: org.cudo.compute.v1.NetworkService.ListNetworks:output_type -> org.cudo.compute.v1.ListNetworksResponse
	15, // 19: org.cudo.compute.v1.NetworkService.DeleteNetwork:output_type -> google.protobuf.Empty
	15, // 20: org.cudo.compute.v1.NetworkService.StartNetwork:output_type -> google.protobuf.Empty
	15, // 21: org.cudo.compute.v1.NetworkService.StopNetwork:output_type -> google.protobuf.Empty
	13, // 22: org.cudo.compute.v1.NetworkService.CreateSecurityGroup:output_type -> org.cudo.compute.v1.SecurityGroup
	13, // 23: org.cudo.compute.v1.NetworkService.GetSecurityGroup:output_type -> org.cudo.compute.v1.SecurityGroup
	2,  // 24: org.cudo.compute.v1.NetworkService.ListSecurityGroups:output_type -> org.cudo.compute.v1.ListSecurityGroupsResponse
	13, // 25: org.cudo.compute.v1.NetworkService.UpdateSecurityGroup:output_type -> org.cudo.compute.v1.SecurityGroup
	15, // 26: org.cudo.compute.v1.NetworkService.DeleteSecurityGroup:output_type -> google.protobuf.Empty
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_svc_compute_network_network_svc_proto_init() }
func file_svc_compute_network_network_svc_proto_init() {
	if File_svc_compute_network_network_svc_proto != nil {
		return
	}
	file_svc_compute_network_network_proto_init()
	file_svc_compute_network_network_svc_proto_msgTypes[1].OneofWrappers = []any{}
	file_svc_compute_network_network_svc_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svc_compute_network_network_svc_proto_rawDesc), len(file_svc_compute_network_network_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svc_compute_network_network_svc_proto_goTypes,
		DependencyIndexes: file_svc_compute_network_network_svc_proto_depIdxs,
		MessageInfos:      file_svc_compute_network_network_svc_proto_msgTypes,
	}.Build()
	File_svc_compute_network_network_svc_proto = out.File
	file_svc_compute_network_network_svc_proto_goTypes = nil
	file_svc_compute_network_network_svc_proto_depIdxs = nil
}
