// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: svc/compute/network/network.proto

package network

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	vm "github.com/CudoVentures/terraform-provider-cudo/internal/compute/vm"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VRouterSize int32

const (
	VRouterSize_VROUTER_INSTANCE_UNKNOWN VRouterSize = 0
	VRouterSize_VROUTER_INSTANCE_SMALL   VRouterSize = 1
	VRouterSize_VROUTER_INSTANCE_MEDIUM  VRouterSize = 2
	VRouterSize_VROUTER_INSTANCE_LARGE   VRouterSize = 3
)

// Enum value maps for VRouterSize.
var (
	VRouterSize_name = map[int32]string{
		0: "VROUTER_INSTANCE_UNKNOWN",
		1: "VROUTER_INSTANCE_SMALL",
		2: "VROUTER_INSTANCE_MEDIUM",
		3: "VROUTER_INSTANCE_LARGE",
	}
	VRouterSize_value = map[string]int32{
		"VROUTER_INSTANCE_UNKNOWN": 0,
		"VROUTER_INSTANCE_SMALL":   1,
		"VROUTER_INSTANCE_MEDIUM":  2,
		"VROUTER_INSTANCE_LARGE":   3,
	}
)

func (x VRouterSize) Enum() *VRouterSize {
	p := new(VRouterSize)
	*p = x
	return p
}

func (x VRouterSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VRouterSize) Descriptor() protoreflect.EnumDescriptor {
	return file_svc_compute_network_network_proto_enumTypes[0].Descriptor()
}

func (VRouterSize) Type() protoreflect.EnumType {
	return &file_svc_compute_network_network_proto_enumTypes[0]
}

func (x VRouterSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VRouterSize.Descriptor instead.
func (VRouterSize) EnumDescriptor() ([]byte, []int) {
	return file_svc_compute_network_network_proto_rawDescGZIP(), []int{0}
}

type Network struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DataCenterId      string                 `protobuf:"bytes,2,opt,name=data_center_id,json=dataCenterId,proto3" json:"data_center_id,omitempty"`
	IpRange           string                 `protobuf:"bytes,3,opt,name=ip_range,json=ipRange,proto3" json:"ip_range,omitempty"`
	Gateway           string                 `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Size              VRouterSize            `protobuf:"varint,5,opt,name=size,proto3,enum=org.cudo.compute.v1.VRouterSize" json:"size,omitempty"`
	PriceHr           *decimal.Decimal       `protobuf:"bytes,6,opt,name=price_hr,json=priceHr,proto3" json:"price_hr,omitempty"`
	ExternalIpAddress string                 `protobuf:"bytes,7,opt,name=external_ip_address,json=externalIpAddress,proto3" json:"external_ip_address,omitempty"`
	InternalIpAddress string                 `protobuf:"bytes,8,opt,name=internal_ip_address,json=internalIpAddress,proto3" json:"internal_ip_address,omitempty"`
	State             vm.VM_VmState          `protobuf:"varint,12,opt,name=state,proto3,enum=org.cudo.compute.v1.VM_VmState" json:"state,omitempty"`
	CreateTime        *timestamppb.Timestamp `protobuf:"bytes,31,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_svc_compute_network_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_network_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_svc_compute_network_network_proto_rawDescGZIP(), []int{0}
}

func (x *Network) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Network) GetDataCenterId() string {
	if x != nil {
		return x.DataCenterId
	}
	return ""
}

func (x *Network) GetIpRange() string {
	if x != nil {
		return x.IpRange
	}
	return ""
}

func (x *Network) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *Network) GetSize() VRouterSize {
	if x != nil {
		return x.Size
	}
	return VRouterSize_VROUTER_INSTANCE_UNKNOWN
}

func (x *Network) GetPriceHr() *decimal.Decimal {
	if x != nil {
		return x.PriceHr
	}
	return nil
}

func (x *Network) GetExternalIpAddress() string {
	if x != nil {
		return x.ExternalIpAddress
	}
	return ""
}

func (x *Network) GetInternalIpAddress() string {
	if x != nil {
		return x.InternalIpAddress
	}
	return ""
}

func (x *Network) GetState() vm.VM_VmState {
	if x != nil {
		return x.State
	}
	return vm.VM_VmState(0)
}

func (x *Network) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

var File_svc_compute_network_network_proto protoreflect.FileDescriptor

const file_svc_compute_network_network_proto_rawDesc = "" +
	"\n" +
	"!svc/compute/network/network.proto\x12\x13org.cudo.compute.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/type/decimal.proto\x1a\x17svc/compute/vm/vm.proto\"\xe4\x03\n" +
	"\aNetwork\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12)\n" +
	"\x0edata_center_id\x18\x02 \x01(\tB\x03\xe0A\x02R\fdataCenterId\x12\x1e\n" +
	"\bip_range\x18\x03 \x01(\tB\x03\xe0A\x02R\aipRange\x12\x1d\n" +
	"\agateway\x18\x04 \x01(\tB\x03\xe0A\x02R\agateway\x129\n" +
	"\x04size\x18\x05 \x01(\x0e2 .org.cudo.compute.v1.VRouterSizeB\x03\xe0A\x02R\x04size\x124\n" +
	"\bprice_hr\x18\x06 \x01(\v2\x14.google.type.DecimalB\x03\xe0A\x02R\apriceHr\x123\n" +
	"\x13external_ip_address\x18\a \x01(\tB\x03\xe0A\x02R\x11externalIpAddress\x123\n" +
	"\x13internal_ip_address\x18\b \x01(\tB\x03\xe0A\x02R\x11internalIpAddress\x12:\n" +
	"\x05state\x18\f \x01(\x0e2\x1f.org.cudo.compute.v1.VM.VmStateB\x03\xe0A\x02R\x05state\x12C\n" +
	"\vcreate_time\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampB\x06\xe0A\x03\xe0A\x02R\n" +
	"createTime*\x80\x01\n" +
	"\vVRouterSize\x12\x1c\n" +
	"\x18VROUTER_INSTANCE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16VROUTER_INSTANCE_SMALL\x10\x01\x12\x1b\n" +
	"\x17VROUTER_INSTANCE_MEDIUM\x10\x02\x12\x1a\n" +
	"\x16VROUTER_INSTANCE_LARGE\x10\x03BAZ?github.com/CudoVentures/cudo-compute-market/svc/compute/networkb\x06proto3"

var (
	file_svc_compute_network_network_proto_rawDescOnce sync.Once
	file_svc_compute_network_network_proto_rawDescData []byte
)

func file_svc_compute_network_network_proto_rawDescGZIP() []byte {
	file_svc_compute_network_network_proto_rawDescOnce.Do(func() {
		file_svc_compute_network_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svc_compute_network_network_proto_rawDesc), len(file_svc_compute_network_network_proto_rawDesc)))
	})
	return file_svc_compute_network_network_proto_rawDescData
}

var file_svc_compute_network_network_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_svc_compute_network_network_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_svc_compute_network_network_proto_goTypes = []any{
	(VRouterSize)(0),              // 0: org.cudo.compute.v1.VRouterSize
	(*Network)(nil),               // 1: org.cudo.compute.v1.Network
	(*decimal.Decimal)(nil),       // 2: google.type.Decimal
	(vm.VM_VmState)(0),            // 3: org.cudo.compute.v1.VM.VmState
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_svc_compute_network_network_proto_depIdxs = []int32{
	0, // 0: org.cudo.compute.v1.Network.size:type_name -> org.cudo.compute.v1.VRouterSize
	2, // 1: org.cudo.compute.v1.Network.price_hr:type_name -> google.type.Decimal
	3, // 2: org.cudo.compute.v1.Network.state:type_name -> org.cudo.compute.v1.VM.VmState
	4, // 3: org.cudo.compute.v1.Network.create_time:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_svc_compute_network_network_proto_init() }
func file_svc_compute_network_network_proto_init() {
	if File_svc_compute_network_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svc_compute_network_network_proto_rawDesc), len(file_svc_compute_network_network_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svc_compute_network_network_proto_goTypes,
		DependencyIndexes: file_svc_compute_network_network_proto_depIdxs,
		EnumInfos:         file_svc_compute_network_network_proto_enumTypes,
		MessageInfos:      file_svc_compute_network_network_proto_msgTypes,
	}.Build()
	File_svc_compute_network_network_proto = out.File
	file_svc_compute_network_network_proto_goTypes = nil
	file_svc_compute_network_network_proto_depIdxs = nil
}
