// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: svc/compute/sshkey/sshkey_svc.proto

package sshkey

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSshKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SshKey        *SshKey                `protobuf:"bytes,1,opt,name=ssh_key,json=sshKey,proto3" json:"ssh_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSshKeyRequest) Reset() {
	*x = CreateSshKeyRequest{}
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSshKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSshKeyRequest) ProtoMessage() {}

func (x *CreateSshKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSshKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateSshKeyRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_sshkey_sshkey_svc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSshKeyRequest) GetSshKey() *SshKey {
	if x != nil {
		return x.SshKey
	}
	return nil
}

type DeleteSshKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSshKeyRequest) Reset() {
	*x = DeleteSshKeyRequest{}
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSshKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSshKeyRequest) ProtoMessage() {}

func (x *DeleteSshKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSshKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteSshKeyRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_sshkey_sshkey_svc_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteSshKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSshKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSshKeyRequest) Reset() {
	*x = GetSshKeyRequest{}
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSshKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSshKeyRequest) ProtoMessage() {}

func (x *GetSshKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSshKeyRequest.ProtoReflect.Descriptor instead.
func (*GetSshKeyRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_sshkey_sshkey_svc_proto_rawDescGZIP(), []int{2}
}

func (x *GetSshKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListProjectSshKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectSshKeysRequest) Reset() {
	*x = ListProjectSshKeysRequest{}
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectSshKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectSshKeysRequest) ProtoMessage() {}

func (x *ListProjectSshKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectSshKeysRequest.ProtoReflect.Descriptor instead.
func (*ListProjectSshKeysRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_sshkey_sshkey_svc_proto_rawDescGZIP(), []int{3}
}

func (x *ListProjectSshKeysRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListProjectSshKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SshKeys       []*SshKey              `protobuf:"bytes,1,rep,name=ssh_keys,json=sshKeys,proto3" json:"ssh_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectSshKeysResponse) Reset() {
	*x = ListProjectSshKeysResponse{}
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectSshKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectSshKeysResponse) ProtoMessage() {}

func (x *ListProjectSshKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectSshKeysResponse.ProtoReflect.Descriptor instead.
func (*ListProjectSshKeysResponse) Descriptor() ([]byte, []int) {
	return file_svc_compute_sshkey_sshkey_svc_proto_rawDescGZIP(), []int{4}
}

func (x *ListProjectSshKeysResponse) GetSshKeys() []*SshKey {
	if x != nil {
		return x.SshKeys
	}
	return nil
}

type ListSshKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNumber    int32                  `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSshKeysRequest) Reset() {
	*x = ListSshKeysRequest{}
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSshKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSshKeysRequest) ProtoMessage() {}

func (x *ListSshKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSshKeysRequest.ProtoReflect.Descriptor instead.
func (*ListSshKeysRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_sshkey_sshkey_svc_proto_rawDescGZIP(), []int{5}
}

func (x *ListSshKeysRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListSshKeysRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSshKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SshKeys       []*SshKey              `protobuf:"bytes,1,rep,name=ssh_keys,json=sshKeys,proto3" json:"ssh_keys,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSshKeysResponse) Reset() {
	*x = ListSshKeysResponse{}
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSshKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSshKeysResponse) ProtoMessage() {}

func (x *ListSshKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_sshkey_sshkey_svc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSshKeysResponse.ProtoReflect.Descriptor instead.
func (*ListSshKeysResponse) Descriptor() ([]byte, []int) {
	return file_svc_compute_sshkey_sshkey_svc_proto_rawDescGZIP(), []int{6}
}

func (x *ListSshKeysResponse) GetSshKeys() []*SshKey {
	if x != nil {
		return x.SshKeys
	}
	return nil
}

func (x *ListSshKeysResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListSshKeysResponse) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListSshKeysResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_svc_compute_sshkey_sshkey_svc_proto protoreflect.FileDescriptor

const file_svc_compute_sshkey_sshkey_svc_proto_rawDesc = "" +
	"\n" +
	"#svc/compute/sshkey/sshkey_svc.proto\x12\x13org.cudo.compute.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1fsvc/compute/sshkey/sshkey.proto\"K\n" +
	"\x13CreateSshKeyRequest\x124\n" +
	"\assh_key\x18\x01 \x01(\v2\x1b.org.cudo.compute.v1.SshKeyR\x06sshKey\"*\n" +
	"\x13DeleteSshKeyRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"'\n" +
	"\x10GetSshKeyRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"?\n" +
	"\x19ListProjectSshKeysRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\"Y\n" +
	"\x1aListProjectSshKeysResponse\x12;\n" +
	"\bssh_keys\x18\x01 \x03(\v2\x1b.org.cudo.compute.v1.SshKeyB\x03\xe0A\x02R\asshKeys\"R\n" +
	"\x12ListSshKeysRequest\x12\x1f\n" +
	"\vpage_number\x18\x01 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xc0\x01\n" +
	"\x13ListSshKeysResponse\x12;\n" +
	"\bssh_keys\x18\x01 \x03(\v2\x1b.org.cudo.compute.v1.SshKeyB\x03\xe0A\x02R\asshKeys\x12$\n" +
	"\vtotal_count\x18\x02 \x01(\x05B\x03\xe0A\x02R\n" +
	"totalCount\x12$\n" +
	"\vpage_number\x18\x03 \x01(\x05B\x03\xe0A\x02R\n" +
	"pageNumber\x12 \n" +
	"\tpage_size\x18\x04 \x01(\x05B\x03\xe0A\x02R\bpageSize2\xb0\x06\n" +
	"\rSshKeyService\x12\x97\x01\n" +
	"\fCreateSshKey\x12(.org.cudo.compute.v1.CreateSshKeyRequest\x1a\x1b.org.cudo.compute.v1.SshKey\"@\xbaG \n" +
	"\bSSH keys\x12\x06Create*\fCreateSshKey\x82\xd3\xe4\x93\x02\x17:\assh_key\"\f/v1/ssh-keys\x12\x8e\x01\n" +
	"\fDeleteSshKey\x12(.org.cudo.compute.v1.DeleteSshKeyRequest\x1a\x16.google.protobuf.Empty\"<\xbaG \n" +
	"\bSSH keys\x12\x06Delete*\fDeleteSshKey\x82\xd3\xe4\x93\x02\x13*\x11/v1/ssh-keys/{id}\x12\x87\x01\n" +
	"\tGetSshKey\x12%.org.cudo.compute.v1.GetSshKeyRequest\x1a\x1b.org.cudo.compute.v1.SshKey\"6\xbaG\x1a\n" +
	"\bSSH keys\x12\x03Get*\tGetSshKey\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/ssh-keys/{id}\x12\xd0\x01\n" +
	"\x12ListProjectSshKeys\x12..org.cudo.compute.v1.ListProjectSshKeysRequest\x1a/.org.cudo.compute.v1.ListProjectSshKeysResponse\"Y\xbaG-\n" +
	"\bProjects\x12\rList SSH keys*\x12ListProjectSshKeys\x82\xd3\xe4\x93\x02#\x12!/v1/project/{project_id}/ssh-keys\x12\x96\x01\n" +
	"\vListSshKeys\x12'.org.cudo.compute.v1.ListSshKeysRequest\x1a(.org.cudo.compute.v1.ListSshKeysResponse\"4\xbaG\x1d\n" +
	"\bSSH keys\x12\x04List*\vListSshKeys\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/ssh-keysBIZGgithub.com/CudoVentures/terraform-provider-cudo/internal/compute/sshkeyb\x06proto3"

var (
	file_svc_compute_sshkey_sshkey_svc_proto_rawDescOnce sync.Once
	file_svc_compute_sshkey_sshkey_svc_proto_rawDescData []byte
)

func file_svc_compute_sshkey_sshkey_svc_proto_rawDescGZIP() []byte {
	file_svc_compute_sshkey_sshkey_svc_proto_rawDescOnce.Do(func() {
		file_svc_compute_sshkey_sshkey_svc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svc_compute_sshkey_sshkey_svc_proto_rawDesc), len(file_svc_compute_sshkey_sshkey_svc_proto_rawDesc)))
	})
	return file_svc_compute_sshkey_sshkey_svc_proto_rawDescData
}

var file_svc_compute_sshkey_sshkey_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_svc_compute_sshkey_sshkey_svc_proto_goTypes = []any{
	(*CreateSshKeyRequest)(nil),        // 0: org.cudo.compute.v1.CreateSshKeyRequest
	(*DeleteSshKeyRequest)(nil),        // 1: org.cudo.compute.v1.DeleteSshKeyRequest
	(*GetSshKeyRequest)(nil),           // 2: org.cudo.compute.v1.GetSshKeyRequest
	(*ListProjectSshKeysRequest)(nil),  // 3: org.cudo.compute.v1.ListProjectSshKeysRequest
	(*ListProjectSshKeysResponse)(nil), // 4: org.cudo.compute.v1.ListProjectSshKeysResponse
	(*ListSshKeysRequest)(nil),         // 5: org.cudo.compute.v1.ListSshKeysRequest
	(*ListSshKeysResponse)(nil),        // 6: org.cudo.compute.v1.ListSshKeysResponse
	(*SshKey)(nil),                     // 7: org.cudo.compute.v1.SshKey
	(*emptypb.Empty)(nil),              // 8: google.protobuf.Empty
}
var file_svc_compute_sshkey_sshkey_svc_proto_depIdxs = []int32{
	7, // 0: org.cudo.compute.v1.CreateSshKeyRequest.ssh_key:type_name -> org.cudo.compute.v1.SshKey
	7, // 1: org.cudo.compute.v1.ListProjectSshKeysResponse.ssh_keys:type_name -> org.cudo.compute.v1.SshKey
	7, // 2: org.cudo.compute.v1.ListSshKeysResponse.ssh_keys:type_name -> org.cudo.compute.v1.SshKey
	0, // 3: org.cudo.compute.v1.SshKeyService.CreateSshKey:input_type -> org.cudo.compute.v1.CreateSshKeyRequest
	1, // 4: org.cudo.compute.v1.SshKeyService.DeleteSshKey:input_type -> org.cudo.compute.v1.DeleteSshKeyRequest
	2, // 5: org.cudo.compute.v1.SshKeyService.GetSshKey:input_type -> org.cudo.compute.v1.GetSshKeyRequest
	3, // 6: org.cudo.compute.v1.SshKeyService.ListProjectSshKeys:input_type -> org.cudo.compute.v1.ListProjectSshKeysRequest
	5, // 7: org.cudo.compute.v1.SshKeyService.ListSshKeys:input_type -> org.cudo.compute.v1.ListSshKeysRequest
	7, // 8: org.cudo.compute.v1.SshKeyService.CreateSshKey:output_type -> org.cudo.compute.v1.SshKey
	8, // 9: org.cudo.compute.v1.SshKeyService.DeleteSshKey:output_type -> google.protobuf.Empty
	7, // 10: org.cudo.compute.v1.SshKeyService.GetSshKey:output_type -> org.cudo.compute.v1.SshKey
	4, // 11: org.cudo.compute.v1.SshKeyService.ListProjectSshKeys:output_type -> org.cudo.compute.v1.ListProjectSshKeysResponse
	6, // 12: org.cudo.compute.v1.SshKeyService.ListSshKeys:output_type -> org.cudo.compute.v1.ListSshKeysResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_svc_compute_sshkey_sshkey_svc_proto_init() }
func file_svc_compute_sshkey_sshkey_svc_proto_init() {
	if File_svc_compute_sshkey_sshkey_svc_proto != nil {
		return
	}
	file_svc_compute_sshkey_sshkey_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svc_compute_sshkey_sshkey_svc_proto_rawDesc), len(file_svc_compute_sshkey_sshkey_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svc_compute_sshkey_sshkey_svc_proto_goTypes,
		DependencyIndexes: file_svc_compute_sshkey_sshkey_svc_proto_depIdxs,
		MessageInfos:      file_svc_compute_sshkey_sshkey_svc_proto_msgTypes,
	}.Build()
	File_svc_compute_sshkey_sshkey_svc_proto = out.File
	file_svc_compute_sshkey_sshkey_svc_proto_goTypes = nil
	file_svc_compute_sshkey_sshkey_svc_proto_depIdxs = nil
}
