// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddBillingAccountUserPermissionBody add billing account user permission body
//
// swagger:model AddBillingAccountUserPermissionBody
type AddBillingAccountUserPermissionBody struct {

	// data center Id
	DataCenterID string `json:"dataCenterId,omitempty"`

	// project Id
	ProjectID string `json:"projectId,omitempty"`

	// role
	// Required: true
	Role *Role `json:"role"`

	// user email
	// Required: true
	UserEmail *string `json:"userEmail"`
}

// Validate validates this add billing account user permission body
func (m *AddBillingAccountUserPermissionBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddBillingAccountUserPermissionBody) validateRole(formats strfmt.Registry) error {

	if err := validate.Required("role", "body", m.Role); err != nil {
		return err
	}

	if err := validate.Required("role", "body", m.Role); err != nil {
		return err
	}

	if m.Role != nil {
		if err := m.Role.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("role")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("role")
			}
			return err
		}
	}

	return nil
}

func (m *AddBillingAccountUserPermissionBody) validateUserEmail(formats strfmt.Registry) error {

	if err := validate.Required("userEmail", "body", m.UserEmail); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this add billing account user permission body based on the context it is used
func (m *AddBillingAccountUserPermissionBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRole(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddBillingAccountUserPermissionBody) contextValidateRole(ctx context.Context, formats strfmt.Registry) error {

	if m.Role != nil {

		if err := m.Role.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("role")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("role")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AddBillingAccountUserPermissionBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddBillingAccountUserPermissionBody) UnmarshalBinary(b []byte) error {
	var res AddBillingAccountUserPermissionBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
