// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RemoveBillingAccountPaymentMethodResponse remove billing account payment method response
//
// swagger:model RemoveBillingAccountPaymentMethodResponse
type RemoveBillingAccountPaymentMethodResponse struct {

	// id
	// Required: true
	ID *string `json:"id"`

	// payment method Id
	// Required: true
	PaymentMethodID *string `json:"paymentMethodId"`
}

// Validate validates this remove billing account payment method response
func (m *RemoveBillingAccountPaymentMethodResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePaymentMethodID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RemoveBillingAccountPaymentMethodResponse) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *RemoveBillingAccountPaymentMethodResponse) validatePaymentMethodID(formats strfmt.Registry) error {

	if err := validate.Required("paymentMethodId", "body", m.PaymentMethodID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this remove billing account payment method response based on context it is used
func (m *RemoveBillingAccountPaymentMethodResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RemoveBillingAccountPaymentMethodResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RemoveBillingAccountPaymentMethodResponse) UnmarshalBinary(b []byte) error {
	var res RemoveBillingAccountPaymentMethodResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
