// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateVMMetadataResponse update VM metadata response
//
// swagger:model UpdateVMMetadataResponse
type UpdateVMMetadataResponse struct {

	// metadata
	Metadata map[string]string `json:"metadata,omitempty"`
}

// Validate validates this update VM metadata response
func (m *UpdateVMMetadataResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update VM metadata response based on context it is used
func (m *UpdateVMMetadataResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateVMMetadataResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateVMMetadataResponse) UnmarshalBinary(b []byte) error {
	var res UpdateVMMetadataResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
