// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// VMDataCenterVRouterSize VM data center v router size
//
// swagger:model VMDataCenter.VRouterSize
type VMDataCenterVRouterSize string

func NewVMDataCenterVRouterSize(value VMDataCenterVRouterSize) *VMDataCenterVRouterSize {
	return &value
}

// Pointer returns a pointer to a freshly-allocated VMDataCenterVRouterSize.
func (m VMDataCenterVRouterSize) Pointer() *VMDataCenterVRouterSize {
	return &m
}

const (

	// VMDataCenterVRouterSizeVROUTERINSTANCEUNKNOWN captures enum value "VROUTER_INSTANCE_UNKNOWN"
	VMDataCenterVRouterSizeVROUTERINSTANCEUNKNOWN VMDataCenterVRouterSize = "VROUTER_INSTANCE_UNKNOWN"

	// VMDataCenterVRouterSizeVROUTERINSTANCESMALL captures enum value "VROUTER_INSTANCE_SMALL"
	VMDataCenterVRouterSizeVROUTERINSTANCESMALL VMDataCenterVRouterSize = "VROUTER_INSTANCE_SMALL"

	// VMDataCenterVRouterSizeVROUTERINSTANCEMEDIUM captures enum value "VROUTER_INSTANCE_MEDIUM"
	VMDataCenterVRouterSizeVROUTERINSTANCEMEDIUM VMDataCenterVRouterSize = "VROUTER_INSTANCE_MEDIUM"

	// VMDataCenterVRouterSizeVROUTERINSTANCELARGE captures enum value "VROUTER_INSTANCE_LARGE"
	VMDataCenterVRouterSizeVROUTERINSTANCELARGE VMDataCenterVRouterSize = "VROUTER_INSTANCE_LARGE"
)

// for schema
var vmDataCenterVRouterSizeEnum []interface{}

func init() {
	var res []VMDataCenterVRouterSize
	if err := json.Unmarshal([]byte(`["VROUTER_INSTANCE_UNKNOWN","VROUTER_INSTANCE_SMALL","VROUTER_INSTANCE_MEDIUM","VROUTER_INSTANCE_LARGE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		vmDataCenterVRouterSizeEnum = append(vmDataCenterVRouterSizeEnum, v)
	}
}

func (m VMDataCenterVRouterSize) validateVMDataCenterVRouterSizeEnum(path, location string, value VMDataCenterVRouterSize) error {
	if err := validate.EnumCase(path, location, value, vmDataCenterVRouterSizeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this VM data center v router size
func (m VMDataCenterVRouterSize) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateVMDataCenterVRouterSizeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this VM data center v router size based on context it is used
func (m VMDataCenterVRouterSize) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
