// Code generated by go-swagger; DO NOT EDIT.

package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// NewUpdateVMMetadataParams creates a new UpdateVMMetadataParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateVMMetadataParams() *UpdateVMMetadataParams {
	return &UpdateVMMetadataParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateVMMetadataParamsWithTimeout creates a new UpdateVMMetadataParams object
// with the ability to set a timeout on a request.
func NewUpdateVMMetadataParamsWithTimeout(timeout time.Duration) *UpdateVMMetadataParams {
	return &UpdateVMMetadataParams{
		timeout: timeout,
	}
}

// NewUpdateVMMetadataParamsWithContext creates a new UpdateVMMetadataParams object
// with the ability to set a context for a request.
func NewUpdateVMMetadataParamsWithContext(ctx context.Context) *UpdateVMMetadataParams {
	return &UpdateVMMetadataParams{
		Context: ctx,
	}
}

// NewUpdateVMMetadataParamsWithHTTPClient creates a new UpdateVMMetadataParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateVMMetadataParamsWithHTTPClient(client *http.Client) *UpdateVMMetadataParams {
	return &UpdateVMMetadataParams{
		HTTPClient: client,
	}
}

/*
UpdateVMMetadataParams contains all the parameters to send to the API endpoint

	for the update VM metadata operation.

	Typically these are written to a http.Request.
*/
type UpdateVMMetadataParams struct {

	// Body.
	Body *models.UpdateVMMetadataBody

	// ID.
	ID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update VM metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateVMMetadataParams) WithDefaults() *UpdateVMMetadataParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update VM metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateVMMetadataParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update VM metadata params
func (o *UpdateVMMetadataParams) WithTimeout(timeout time.Duration) *UpdateVMMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update VM metadata params
func (o *UpdateVMMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update VM metadata params
func (o *UpdateVMMetadataParams) WithContext(ctx context.Context) *UpdateVMMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update VM metadata params
func (o *UpdateVMMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update VM metadata params
func (o *UpdateVMMetadataParams) WithHTTPClient(client *http.Client) *UpdateVMMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update VM metadata params
func (o *UpdateVMMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update VM metadata params
func (o *UpdateVMMetadataParams) WithBody(body *models.UpdateVMMetadataBody) *UpdateVMMetadataParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update VM metadata params
func (o *UpdateVMMetadataParams) SetBody(body *models.UpdateVMMetadataBody) {
	o.Body = body
}

// WithID adds the id to the update VM metadata params
func (o *UpdateVMMetadataParams) WithID(id string) *UpdateVMMetadataParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update VM metadata params
func (o *UpdateVMMetadataParams) SetID(id string) {
	o.ID = id
}

// WithProjectID adds the projectID to the update VM metadata params
func (o *UpdateVMMetadataParams) WithProjectID(projectID string) *UpdateVMMetadataParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the update VM metadata params
func (o *UpdateVMMetadataParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateVMMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
