// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: svc/compute/baremetal/baremetal_svc.proto

package baremetal

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMachineInstanceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MachineInstance *MachineInstance       `protobuf:"bytes,1,opt,name=machine_instance,json=machineInstance,proto3" json:"machine_instance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateMachineInstanceRequest) Reset() {
	*x = CreateMachineInstanceRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMachineInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMachineInstanceRequest) ProtoMessage() {}

func (x *CreateMachineInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMachineInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateMachineInstanceRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMachineInstanceRequest) GetMachineInstance() *MachineInstance {
	if x != nil {
		return x.MachineInstance
	}
	return nil
}

type DeleteMachineInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMachineInstanceRequest) Reset() {
	*x = DeleteMachineInstanceRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMachineInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMachineInstanceRequest) ProtoMessage() {}

func (x *DeleteMachineInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMachineInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteMachineInstanceRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteMachineInstanceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteMachineInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMachineInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineInstanceRequest) Reset() {
	*x = GetMachineInstanceRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineInstanceRequest) ProtoMessage() {}

func (x *GetMachineInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetMachineInstanceRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{2}
}

func (x *GetMachineInstanceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetMachineInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListMachineInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachineInstancesRequest) Reset() {
	*x = ListMachineInstancesRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachineInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachineInstancesRequest) ProtoMessage() {}

func (x *ListMachineInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachineInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListMachineInstancesRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{3}
}

func (x *ListMachineInstancesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListMachineInstancesRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListMachineInstancesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMachineInstancesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MachineInstances []*MachineInstance     `protobuf:"bytes,1,rep,name=machine_instances,json=machineInstances,proto3" json:"machine_instances,omitempty"`
	TotalCount       int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PageNumber       int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize         int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListMachineInstancesResponse) Reset() {
	*x = ListMachineInstancesResponse{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachineInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachineInstancesResponse) ProtoMessage() {}

func (x *ListMachineInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachineInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListMachineInstancesResponse) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{4}
}

func (x *ListMachineInstancesResponse) GetMachineInstances() []*MachineInstance {
	if x != nil {
		return x.MachineInstances
	}
	return nil
}

func (x *ListMachineInstancesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListMachineInstancesResponse) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListMachineInstancesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateMachineInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The machine instance to update.
	//
	// The machine instance's `project_id` and `id` fields are used to identify the machine instance to update.
	MachineInstance *MachineInstance `protobuf:"bytes,1,opt,name=machine_instance,json=machineInstance,proto3" json:"machine_instance,omitempty"`
	// The list of fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMachineInstanceRequest) Reset() {
	*x = UpdateMachineInstanceRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMachineInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMachineInstanceRequest) ProtoMessage() {}

func (x *UpdateMachineInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMachineInstanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateMachineInstanceRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMachineInstanceRequest) GetMachineInstance() *MachineInstance {
	if x != nil {
		return x.MachineInstance
	}
	return nil
}

func (x *UpdateMachineInstanceRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeployMachineInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	UserData      string                 `protobuf:"bytes,4,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployMachineInstanceRequest) Reset() {
	*x = DeployMachineInstanceRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployMachineInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployMachineInstanceRequest) ProtoMessage() {}

func (x *DeployMachineInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployMachineInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeployMachineInstanceRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{6}
}

func (x *DeployMachineInstanceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeployMachineInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeployMachineInstanceRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *DeployMachineInstanceRequest) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

type UndeployMachineInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeployMachineInstanceRequest) Reset() {
	*x = UndeployMachineInstanceRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeployMachineInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeployMachineInstanceRequest) ProtoMessage() {}

func (x *UndeployMachineInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeployMachineInstanceRequest.ProtoReflect.Descriptor instead.
func (*UndeployMachineInstanceRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{7}
}

func (x *UndeployMachineInstanceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UndeployMachineInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EraseMachineInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EraseMachineInstanceRequest) Reset() {
	*x = EraseMachineInstanceRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EraseMachineInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EraseMachineInstanceRequest) ProtoMessage() {}

func (x *EraseMachineInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EraseMachineInstanceRequest.ProtoReflect.Descriptor instead.
func (*EraseMachineInstanceRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{8}
}

func (x *EraseMachineInstanceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *EraseMachineInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PowerOnMachineInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	UserData      string                 `protobuf:"bytes,3,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerOnMachineInstanceRequest) Reset() {
	*x = PowerOnMachineInstanceRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerOnMachineInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerOnMachineInstanceRequest) ProtoMessage() {}

func (x *PowerOnMachineInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerOnMachineInstanceRequest.ProtoReflect.Descriptor instead.
func (*PowerOnMachineInstanceRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{9}
}

func (x *PowerOnMachineInstanceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PowerOnMachineInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PowerOnMachineInstanceRequest) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

type PowerOffMachineInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerOffMachineInstanceRequest) Reset() {
	*x = PowerOffMachineInstanceRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerOffMachineInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerOffMachineInstanceRequest) ProtoMessage() {}

func (x *PowerOffMachineInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerOffMachineInstanceRequest.ProtoReflect.Descriptor instead.
func (*PowerOffMachineInstanceRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{10}
}

func (x *PowerOffMachineInstanceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PowerOffMachineInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PowerOffMachineInstanceRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ListMachineTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNumber    int32                  `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachineTypesRequest) Reset() {
	*x = ListMachineTypesRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachineTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachineTypesRequest) ProtoMessage() {}

func (x *ListMachineTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachineTypesRequest.ProtoReflect.Descriptor instead.
func (*ListMachineTypesRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{11}
}

func (x *ListMachineTypesRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListMachineTypesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMachineTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineTypes  []*MachineType         `protobuf:"bytes,1,rep,name=machine_types,json=machineTypes,proto3" json:"machine_types,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachineTypesResponse) Reset() {
	*x = ListMachineTypesResponse{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachineTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachineTypesResponse) ProtoMessage() {}

func (x *ListMachineTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachineTypesResponse.ProtoReflect.Descriptor instead.
func (*ListMachineTypesResponse) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{12}
}

func (x *ListMachineTypesResponse) GetMachineTypes() []*MachineType {
	if x != nil {
		return x.MachineTypes
	}
	return nil
}

func (x *ListMachineTypesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListMachineTypesResponse) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListMachineTypesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMachineOperatingSystemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachineOperatingSystemsRequest) Reset() {
	*x = ListMachineOperatingSystemsRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachineOperatingSystemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachineOperatingSystemsRequest) ProtoMessage() {}

func (x *ListMachineOperatingSystemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachineOperatingSystemsRequest.ProtoReflect.Descriptor instead.
func (*ListMachineOperatingSystemsRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{13}
}

type ListMachineOperatingSystemsResponse struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Images        []*ListMachineOperatingSystemsResponse_Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachineOperatingSystemsResponse) Reset() {
	*x = ListMachineOperatingSystemsResponse{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachineOperatingSystemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachineOperatingSystemsResponse) ProtoMessage() {}

func (x *ListMachineOperatingSystemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachineOperatingSystemsResponse.ProtoReflect.Descriptor instead.
func (*ListMachineOperatingSystemsResponse) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{14}
}

func (x *ListMachineOperatingSystemsResponse) GetImages() []*ListMachineOperatingSystemsResponse_Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterRequest) Reset() {
	*x = CreateClusterRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterRequest) ProtoMessage() {}

func (x *CreateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateClusterRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{15}
}

func (x *CreateClusterRequest) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type DeleteClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClusterRequest) Reset() {
	*x = DeleteClusterRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClusterRequest) ProtoMessage() {}

func (x *DeleteClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClusterRequest.ProtoReflect.Descriptor instead.
func (*DeleteClusterRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteClusterRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteClusterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterRequest) Reset() {
	*x = GetClusterRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterRequest) ProtoMessage() {}

func (x *GetClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterRequest.ProtoReflect.Descriptor instead.
func (*GetClusterRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{17}
}

func (x *GetClusterRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetClusterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListClustersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersRequest) Reset() {
	*x = ListClustersRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersRequest) ProtoMessage() {}

func (x *ListClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersRequest.ProtoReflect.Descriptor instead.
func (*ListClustersRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{18}
}

func (x *ListClustersRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListClustersRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListClustersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListClustersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*Cluster             `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersResponse) Reset() {
	*x = ListClustersResponse{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersResponse) ProtoMessage() {}

func (x *ListClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersResponse.ProtoReflect.Descriptor instead.
func (*ListClustersResponse) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{19}
}

func (x *ListClustersResponse) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ListClustersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListClustersResponse) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListClustersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateClusterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cluster to update.
	//
	// The cluster's `project_id` and `id` fields are used to identify the cluster to update.
	Cluster *Cluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// The list of fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterRequest) Reset() {
	*x = UpdateClusterRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterRequest) ProtoMessage() {}

func (x *UpdateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterRequest.ProtoReflect.Descriptor instead.
func (*UpdateClusterRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateClusterRequest) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *UpdateClusterRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateClusterMachineRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cluster machine to update.
	//
	// The cluster machine's `project_id` and `id` fields are used to identify the cluster machine to update.
	ClusterMachine *ClusterMachine `protobuf:"bytes,1,opt,name=cluster_machine,json=clusterMachine,proto3" json:"cluster_machine,omitempty"`
	// The list of fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterMachineRequest) Reset() {
	*x = UpdateClusterMachineRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterMachineRequest) ProtoMessage() {}

func (x *UpdateClusterMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterMachineRequest.ProtoReflect.Descriptor instead.
func (*UpdateClusterMachineRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateClusterMachineRequest) GetClusterMachine() *ClusterMachine {
	if x != nil {
		return x.ClusterMachine
	}
	return nil
}

func (x *UpdateClusterMachineRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type RebootClusterMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootClusterMachineRequest) Reset() {
	*x = RebootClusterMachineRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootClusterMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootClusterMachineRequest) ProtoMessage() {}

func (x *RebootClusterMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootClusterMachineRequest.ProtoReflect.Descriptor instead.
func (*RebootClusterMachineRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{22}
}

func (x *RebootClusterMachineRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RebootClusterMachineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RenameClusterMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	NewId         string                 `protobuf:"bytes,3,opt,name=new_id,json=newId,proto3" json:"new_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameClusterMachineRequest) Reset() {
	*x = RenameClusterMachineRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameClusterMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameClusterMachineRequest) ProtoMessage() {}

func (x *RenameClusterMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameClusterMachineRequest.ProtoReflect.Descriptor instead.
func (*RenameClusterMachineRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{23}
}

func (x *RenameClusterMachineRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RenameClusterMachineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenameClusterMachineRequest) GetNewId() string {
	if x != nil {
		return x.NewId
	}
	return ""
}

type DeleteClusterMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClusterMachineRequest) Reset() {
	*x = DeleteClusterMachineRequest{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClusterMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClusterMachineRequest) ProtoMessage() {}

func (x *DeleteClusterMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClusterMachineRequest.ProtoReflect.Descriptor instead.
func (*DeleteClusterMachineRequest) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteClusterMachineRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteClusterMachineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListMachineOperatingSystemsResponse_Image struct {
	state             protoimpl.MessageState                               `protogen:"open.v1"`
	Id                string                                               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                                               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                                               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DisplayName       string                                               `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Platform          string                                               `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	SizeGib           int32                                                `protobuf:"varint,7,opt,name=size_gib,json=sizeGib,proto3" json:"size_gib,omitempty"`
	InstalledPackages []*ListMachineOperatingSystemsResponse_Image_Package `protobuf:"bytes,8,rep,name=installed_packages,json=installedPackages,proto3" json:"installed_packages,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListMachineOperatingSystemsResponse_Image) Reset() {
	*x = ListMachineOperatingSystemsResponse_Image{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachineOperatingSystemsResponse_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachineOperatingSystemsResponse_Image) ProtoMessage() {}

func (x *ListMachineOperatingSystemsResponse_Image) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachineOperatingSystemsResponse_Image.ProtoReflect.Descriptor instead.
func (*ListMachineOperatingSystemsResponse_Image) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{14, 0}
}

func (x *ListMachineOperatingSystemsResponse_Image) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListMachineOperatingSystemsResponse_Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListMachineOperatingSystemsResponse_Image) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListMachineOperatingSystemsResponse_Image) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ListMachineOperatingSystemsResponse_Image) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ListMachineOperatingSystemsResponse_Image) GetSizeGib() int32 {
	if x != nil {
		return x.SizeGib
	}
	return 0
}

func (x *ListMachineOperatingSystemsResponse_Image) GetInstalledPackages() []*ListMachineOperatingSystemsResponse_Image_Package {
	if x != nil {
		return x.InstalledPackages
	}
	return nil
}

type ListMachineOperatingSystemsResponse_Image_Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachineOperatingSystemsResponse_Image_Package) Reset() {
	*x = ListMachineOperatingSystemsResponse_Image_Package{}
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachineOperatingSystemsResponse_Image_Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachineOperatingSystemsResponse_Image_Package) ProtoMessage() {}

func (x *ListMachineOperatingSystemsResponse_Image_Package) ProtoReflect() protoreflect.Message {
	mi := &file_svc_compute_baremetal_baremetal_svc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachineOperatingSystemsResponse_Image_Package.ProtoReflect.Descriptor instead.
func (*ListMachineOperatingSystemsResponse_Image_Package) Descriptor() ([]byte, []int) {
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP(), []int{14, 0, 0}
}

func (x *ListMachineOperatingSystemsResponse_Image_Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListMachineOperatingSystemsResponse_Image_Package) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListMachineOperatingSystemsResponse_Image_Package) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_svc_compute_baremetal_baremetal_svc_proto protoreflect.FileDescriptor

const file_svc_compute_baremetal_baremetal_svc_proto_rawDesc = "" +
	"\n" +
	")svc/compute/baremetal/baremetal_svc.proto\x12\x13org.cudo.compute.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x19google/type/decimal.proto\x1a$gnostic/openapi/v3/annotations.proto\x1a%svc/compute/baremetal/baremetal.proto\"t\n" +
	"\x1cCreateMachineInstanceRequest\x12T\n" +
	"\x10machine_instance\x18\x01 \x01(\v2$.org.cudo.compute.v1.MachineInstanceB\x03\xe0A\x02R\x0fmachineInstance\"W\n" +
	"\x1cDeleteMachineInstanceRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\"T\n" +
	"\x19GetMachineInstanceRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\"\x7f\n" +
	"\x1bListMachineInstancesRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xdf\x01\n" +
	"\x1cListMachineInstancesResponse\x12Q\n" +
	"\x11machine_instances\x18\x01 \x03(\v2$.org.cudo.compute.v1.MachineInstanceR\x10machineInstances\x12$\n" +
	"\vtotal_count\x18\x02 \x01(\x05B\x03\xe0A\x02R\n" +
	"totalCount\x12$\n" +
	"\vpage_number\x18\x03 \x01(\x05B\x03\xe0A\x02R\n" +
	"pageNumber\x12 \n" +
	"\tpage_size\x18\x04 \x01(\x05B\x03\xe0A\x02R\bpageSize\"\xb1\x01\n" +
	"\x1cUpdateMachineInstanceRequest\x12T\n" +
	"\x10machine_instance\x18\x01 \x01(\v2$.org.cudo.compute.v1.MachineInstanceB\x03\xe0A\x02R\x0fmachineInstance\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x89\x01\n" +
	"\x1cDeployMachineInstanceRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\x12\x13\n" +
	"\x02os\x18\x03 \x01(\tB\x03\xe0A\x02R\x02os\x12\x1b\n" +
	"\tuser_data\x18\x04 \x01(\tR\buserData\"Y\n" +
	"\x1eUndeployMachineInstanceRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\"V\n" +
	"\x1bEraseMachineInstanceRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\"u\n" +
	"\x1dPowerOnMachineInstanceRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\x12\x1b\n" +
	"\tuser_data\x18\x03 \x01(\tR\buserData\"o\n" +
	"\x1ePowerOffMachineInstanceRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"W\n" +
	"\x17ListMachineTypesRequest\x12\x1f\n" +
	"\vpage_number\x18\x01 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xcf\x01\n" +
	"\x18ListMachineTypesResponse\x12E\n" +
	"\rmachine_types\x18\x01 \x03(\v2 .org.cudo.compute.v1.MachineTypeR\fmachineTypes\x12$\n" +
	"\vtotal_count\x18\x02 \x01(\x05B\x03\xe0A\x02R\n" +
	"totalCount\x12$\n" +
	"\vpage_number\x18\x03 \x01(\x05B\x03\xe0A\x02R\n" +
	"pageNumber\x12 \n" +
	"\tpage_size\x18\x04 \x01(\x05B\x03\xe0A\x02R\bpageSize\"$\n" +
	"\"ListMachineOperatingSystemsRequest\"\xb0\x04\n" +
	"#ListMachineOperatingSystemsResponse\x12[\n" +
	"\x06images\x18\x01 \x03(\v2>.org.cudo.compute.v1.ListMachineOperatingSystemsResponse.ImageB\x03\xe0A\x02R\x06images\x1a\xab\x03\n" +
	"\x05Image\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tB\x03\xe0A\x02R\vdescription\x12&\n" +
	"\fdisplay_name\x18\x04 \x01(\tB\x03\xe0A\x02R\vdisplayName\x12\x1f\n" +
	"\bplatform\x18\x05 \x01(\tB\x03\xe0A\x02R\bplatform\x12\x1e\n" +
	"\bsize_gib\x18\a \x01(\x05B\x03\xe0A\x02R\asizeGib\x12z\n" +
	"\x12installed_packages\x18\b \x03(\v2F.org.cudo.compute.v1.ListMachineOperatingSystemsResponse.Image.PackageB\x03\xe0A\x02R\x11installedPackages\x1ah\n" +
	"\aPackage\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tB\x03\xe0A\x02R\vdescription\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\tB\x03\xe0A\x02R\aversion\"S\n" +
	"\x14CreateClusterRequest\x12;\n" +
	"\acluster\x18\x01 \x01(\v2\x1c.org.cudo.compute.v1.ClusterB\x03\xe0A\x02R\acluster\"O\n" +
	"\x14DeleteClusterRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\"L\n" +
	"\x11GetClusterRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\"w\n" +
	"\x13ListClustersRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xbe\x01\n" +
	"\x14ListClustersResponse\x128\n" +
	"\bclusters\x18\x01 \x03(\v2\x1c.org.cudo.compute.v1.ClusterR\bclusters\x12$\n" +
	"\vtotal_count\x18\x02 \x01(\x05B\x03\xe0A\x02R\n" +
	"totalCount\x12$\n" +
	"\vpage_number\x18\x03 \x01(\x05B\x03\xe0A\x02R\n" +
	"pageNumber\x12 \n" +
	"\tpage_size\x18\x04 \x01(\x05B\x03\xe0A\x02R\bpageSize\"\x90\x01\n" +
	"\x14UpdateClusterRequest\x12;\n" +
	"\acluster\x18\x01 \x01(\v2\x1c.org.cudo.compute.v1.ClusterB\x03\xe0A\x02R\acluster\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\xad\x01\n" +
	"\x1bUpdateClusterMachineRequest\x12Q\n" +
	"\x0fcluster_machine\x18\x01 \x01(\v2#.org.cudo.compute.v1.ClusterMachineB\x03\xe0A\x02R\x0eclusterMachine\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"V\n" +
	"\x1bRebootClusterMachineRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\"r\n" +
	"\x1bRenameClusterMachineRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\x12\x1a\n" +
	"\x06new_id\x18\x03 \x01(\tB\x03\xe0A\x02R\x05newId\"V\n" +
	"\x1bDeleteClusterMachineRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id2\xaf0\n" +
	"\x10BareMetalService\x12\xa9\x02\n" +
	"\x15CreateMachineInstance\x121.org.cudo.compute.v1.CreateMachineInstanceRequest\x1a$.org.cudo.compute.v1.MachineInstance\"\xb6\x01\xbaG]\n" +
	"\n" +
	"Bare metal\x12\x19Create a machine instance\x1a\x1dOrder a machine for a project*\x15CreateMachineInstance\x82\xd3\xe4\x93\x02P:\x10machine_instance\"</v1/projects/{machine_instance.project_id}/machine-instances\x12\xd7\x02\n" +
	"\x15DeleteMachineInstance\x121.org.cudo.compute.v1.DeleteMachineInstanceRequest\x1a\x16.google.protobuf.Empty\"\xf2\x01\xbaG\xb6\x01\n" +
	"\n" +
	"Bare metal\x12\x19Delete a machine instance\x1avDelete a machine instance from a project. Machine instances that are still within a commitment term cannot be deleted.*\x15DeleteMachineInstance\x82\xd3\xe4\x93\x022*0/v1/projects/{project_id}/machine-instances/{id}\x12\x87\x02\n" +
	"\x12GetMachineInstance\x12..org.cudo.compute.v1.GetMachineInstanceRequest\x1a$.org.cudo.compute.v1.MachineInstance\"\x9a\x01\xbaG_\n" +
	"\n" +
	"Bare metal\x12\x16Get a machine instance\x1a%Get the details of a machine instance*\x12GetMachineInstance\x82\xd3\xe4\x93\x022\x120/v1/projects/{project_id}/machine-instances/{id}\x12\x93\x02\n" +
	"\x14ListMachineInstances\x120.org.cudo.compute.v1.ListMachineInstancesRequest\x1a1.org.cudo.compute.v1.ListMachineInstancesResponse\"\x95\x01\xbaG_\n" +
	"\n" +
	"Bare metal\x12\x16List machine instances\x1a#List machine instances in a project*\x14ListMachineInstances\x82\xd3\xe4\x93\x02-\x12+/v1/projects/{project_id}/machine-instances\x12\xc8\x02\n" +
	"\x15UpdateMachineInstance\x121.org.cudo.compute.v1.UpdateMachineInstanceRequest\x1a$.org.cudo.compute.v1.MachineInstance\"\xd5\x01\xbaGf\n" +
	"\n" +
	"Bare metal\x12\x19Update a machine instance\x1a&Update a machine instance in a project*\x15UpdateMachineInstance\x82\xd3\xe4\x93\x02f:\x10machine_instance2R/v1/projects/{machine_instance.project_id}/machine-instances/{machine_instance.id}\x12\x93\x02\n" +
	"\x17PowerOffMachineInstance\x123.org.cudo.compute.v1.PowerOffMachineInstanceRequest\x1a\x16.google.protobuf.Empty\"\xaa\x01\xbaGn\n" +
	"\n" +
	"Bare metal\x12\x1cPower off a machine instance\x1a)Power off a machine instance in a project*\x17PowerOffMachineInstance\x82\xd3\xe4\x93\x023\"1/v1/projects/{project_id}/machines/{id}/power-off\x12\x8d\x02\n" +
	"\x16PowerOnMachineInstance\x122.org.cudo.compute.v1.PowerOnMachineInstanceRequest\x1a\x16.google.protobuf.Empty\"\xa6\x01\xbaGk\n" +
	"\n" +
	"Bare metal\x12\x1bPower on a machine instance\x1a(Power on a machine instance in a project*\x16PowerOnMachineInstance\x82\xd3\xe4\x93\x022\"0/v1/projects/{project_id}/machines/{id}/power-on\x12\x8e\x02\n" +
	"\x15DeployMachineInstance\x121.org.cudo.compute.v1.DeployMachineInstanceRequest\x1a\x16.google.protobuf.Empty\"\xa9\x01\xbaGp\n" +
	"\n" +
	"Bare metal\x12\x17Deploy operating system\x1a2Deploy an operating system onto a machine instance*\x15DeployMachineInstance\x82\xd3\xe4\x93\x020\"./v1/projects/{project_id}/machines/{id}/deploy\x12\xa2\x02\n" +
	"\x17UndeployMachineInstance\x123.org.cudo.compute.v1.UndeployMachineInstanceRequest\x1a\x16.google.protobuf.Empty\"\xb9\x01\xbaG~\n" +
	"\n" +
	"Bare metal\x12\x0fRelease machine\x1aFReleases a machine instance allowing subsequent deployment of a new OS*\x17UndeployMachineInstance\x82\xd3\xe4\x93\x022\"0/v1/projects/{project_id}/machines/{id}/undeploy\x12\x82\x02\n" +
	"\x14EraseMachineInstance\x120.org.cudo.compute.v1.EraseMachineInstanceRequest\x1a\x16.google.protobuf.Empty\"\x9f\x01\xbaGg\n" +
	"\n" +
	"Bare metal\x12\x1cErase machine instance disks\x1a%Erase all disks in a machine instance*\x14EraseMachineInstance\x82\xd3\xe4\x93\x02/\"-/v1/projects/{project_id}/machines/{id}/erase\x12\xc0\x02\n" +
	"\x1bListMachineOperatingSystems\x127.org.cudo.compute.v1.ListMachineOperatingSystemsRequest\x1a8.org.cudo.compute.v1.ListMachineOperatingSystemsResponse\"\xad\x01\xbaG\x83\x01\n" +
	"\n" +
	"Bare metal\x12\x16List operating systems\x1a@List operating systems that can be deployed to machine instances*\x1bListMachineOperatingSystems\x82\xd3\xe4\x93\x02 \x12\x1e/v1/machines/operating-systems\x12\xe8\x01\n" +
	"\x10ListMachineTypes\x12,.org.cudo.compute.v1.ListMachineTypesRequest\x1a-.org.cudo.compute.v1.ListMachineTypesResponse\"w\xbaGZ\n" +
	"\n" +
	"Bare metal\x12\x12List machine types\x1a&List machine types that can be ordered*\x10ListMachineTypes\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/machines-types\x12\xec\x01\n" +
	"\x17ListClusterMachineTypes\x123.org.cudo.compute.v1.ListClusterMachineTypesRequest\x1a4.org.cudo.compute.v1.ListClusterMachineTypesResponse\"f\xbaGA\n" +
	"\n" +
	"Bare Metal\x12\x1aList cluster machine types*\x17ListClusterMachineTypes\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/clusters/machine-types\x12\x93\x02\n" +
	"\x15GetClusterMachineType\x121.org.cudo.compute.v1.GetClusterMachineTypeRequest\x1a2.org.cudo.compute.v1.GetClusterMachineTypeResponse\"\x92\x01\xbaG=\n" +
	"\n" +
	"Bare Metal\x12\x18Get cluster machine type*\x15GetClusterMachineType\x82\xd3\xe4\x93\x02L\x12J/v1/clusters/data-centers/{data_center_id}/machine-types/{machine_type_id}\x12\xe5\x01\n" +
	"\rCreateCluster\x12).org.cudo.compute.v1.CreateClusterRequest\x1a\x1c.org.cudo.compute.v1.Cluster\"\x8a\x01\xbaGL\n" +
	"\n" +
	"Bare Metal\x12\x10Create a cluster\x1a\x1dOrder a cluster for a project*\rCreateCluster\x82\xd3\xe4\x93\x025:\acluster\"*/v1/projects/{cluster.project_id}/clusters\x12\xd6\x01\n" +
	"\rDeleteCluster\x12).org.cudo.compute.v1.DeleteClusterRequest\x1a\x16.google.protobuf.Empty\"\x81\x01\xbaGO\n" +
	"\n" +
	"Bare Metal\x12\x10Delete a cluster\x1a Delete a cluster from a project.*\rDeleteCluster\x82\xd3\xe4\x93\x02)*'/v1/projects/{project_id}/clusters/{id}\x12\xcb\x01\n" +
	"\n" +
	"GetCluster\x12&.org.cudo.compute.v1.GetClusterRequest\x1a\x1c.org.cudo.compute.v1.Cluster\"w\xbaGE\n" +
	"\n" +
	"Bare Metal\x12\rGet a cluster\x1a\x1cGet the details of a cluster*\n" +
	"GetCluster\x82\xd3\xe4\x93\x02)\x12'/v1/projects/{project_id}/clusters/{id}\x12\xd7\x01\n" +
	"\fListClusters\x12(.org.cudo.compute.v1.ListClustersRequest\x1a).org.cudo.compute.v1.ListClustersResponse\"r\xbaGE\n" +
	"\n" +
	"Bare Metal\x12\rList clusters\x1a\x1aList clusters in a project*\fListClusters\x82\xd3\xe4\x93\x02$\x12\"/v1/projects/{project_id}/clusters\x12\xf2\x01\n" +
	"\rUpdateCluster\x12).org.cudo.compute.v1.UpdateClusterRequest\x1a\x1c.org.cudo.compute.v1.Cluster\"\x97\x01\xbaGL\n" +
	"\n" +
	"Bare Metal\x12\x10Update a cluster\x1a\x1dUpdate a cluster in a project*\rUpdateCluster\x82\xd3\xe4\x93\x02B:\acluster27/v1/projects/{cluster.project_id}/clusters/{cluster.id}\x12\xfa\x01\n" +
	"\x14DeleteClusterMachine\x120.org.cudo.compute.v1.DeleteClusterMachineRequest\x1a\x16.google.protobuf.Empty\"\x97\x01\xbaG]\n" +
	"\n" +
	"Bare Metal\x12\x18Delete a cluster machine\x1a\x1fDelete a machine from a cluster*\x14DeleteClusterMachine\x82\xd3\xe4\x93\x021*//v1/projects/{project_id}/cluster-machines/{id}\x12\xff\x01\n" +
	"\x14RebootClusterMachine\x120.org.cudo.compute.v1.RebootClusterMachineRequest\x1a\x16.google.protobuf.Empty\"\x9c\x01\xbaG[\n" +
	"\n" +
	"Bare Metal\x12\x18Reboot a cluster machine\x1a\x1dReboot a machine in a cluster*\x14RebootClusterMachine\x82\xd3\xe4\x93\x028\"6/v1/projects/{project_id}/cluster-machines/{id}:reboot\x12\xff\x01\n" +
	"\x14RenameClusterMachine\x120.org.cudo.compute.v1.RenameClusterMachineRequest\x1a\x16.google.protobuf.Empty\"\x9c\x01\xbaG[\n" +
	"\n" +
	"Bare Metal\x12\x18Rename a cluster machine\x1a\x1dRename a machine in a cluster*\x14RenameClusterMachine\x82\xd3\xe4\x93\x028\"6/v1/projects/{project_id}/cluster-machines/{id}:rename\x12\xb6\x02\n" +
	"\x14UpdateClusterMachine\x120.org.cudo.compute.v1.UpdateClusterMachineRequest\x1a#.org.cudo.compute.v1.ClusterMachine\"\xc6\x01\xbaG[\n" +
	"\n" +
	"Bare Metal\x12\x18Update a cluster machine\x1a\x1dUpdate a machine in a cluster*\x14UpdateClusterMachine\x82\xd3\xe4\x93\x02b:\x0fcluster_machine2O/v1/projects/{cluster_machine.project_id}/cluster-machines/{cluster_machine.id}BLZJgithub.com/CudoVentures/terraform-provider-cudo/internal/compute/baremetalb\x06proto3"

var (
	file_svc_compute_baremetal_baremetal_svc_proto_rawDescOnce sync.Once
	file_svc_compute_baremetal_baremetal_svc_proto_rawDescData []byte
)

func file_svc_compute_baremetal_baremetal_svc_proto_rawDescGZIP() []byte {
	file_svc_compute_baremetal_baremetal_svc_proto_rawDescOnce.Do(func() {
		file_svc_compute_baremetal_baremetal_svc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svc_compute_baremetal_baremetal_svc_proto_rawDesc), len(file_svc_compute_baremetal_baremetal_svc_proto_rawDesc)))
	})
	return file_svc_compute_baremetal_baremetal_svc_proto_rawDescData
}

var file_svc_compute_baremetal_baremetal_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_svc_compute_baremetal_baremetal_svc_proto_goTypes = []any{
	(*CreateMachineInstanceRequest)(nil),                      // 0: org.cudo.compute.v1.CreateMachineInstanceRequest
	(*DeleteMachineInstanceRequest)(nil),                      // 1: org.cudo.compute.v1.DeleteMachineInstanceRequest
	(*GetMachineInstanceRequest)(nil),                         // 2: org.cudo.compute.v1.GetMachineInstanceRequest
	(*ListMachineInstancesRequest)(nil),                       // 3: org.cudo.compute.v1.ListMachineInstancesRequest
	(*ListMachineInstancesResponse)(nil),                      // 4: org.cudo.compute.v1.ListMachineInstancesResponse
	(*UpdateMachineInstanceRequest)(nil),                      // 5: org.cudo.compute.v1.UpdateMachineInstanceRequest
	(*DeployMachineInstanceRequest)(nil),                      // 6: org.cudo.compute.v1.DeployMachineInstanceRequest
	(*UndeployMachineInstanceRequest)(nil),                    // 7: org.cudo.compute.v1.UndeployMachineInstanceRequest
	(*EraseMachineInstanceRequest)(nil),                       // 8: org.cudo.compute.v1.EraseMachineInstanceRequest
	(*PowerOnMachineInstanceRequest)(nil),                     // 9: org.cudo.compute.v1.PowerOnMachineInstanceRequest
	(*PowerOffMachineInstanceRequest)(nil),                    // 10: org.cudo.compute.v1.PowerOffMachineInstanceRequest
	(*ListMachineTypesRequest)(nil),                           // 11: org.cudo.compute.v1.ListMachineTypesRequest
	(*ListMachineTypesResponse)(nil),                          // 12: org.cudo.compute.v1.ListMachineTypesResponse
	(*ListMachineOperatingSystemsRequest)(nil),                // 13: org.cudo.compute.v1.ListMachineOperatingSystemsRequest
	(*ListMachineOperatingSystemsResponse)(nil),               // 14: org.cudo.compute.v1.ListMachineOperatingSystemsResponse
	(*CreateClusterRequest)(nil),                              // 15: org.cudo.compute.v1.CreateClusterRequest
	(*DeleteClusterRequest)(nil),                              // 16: org.cudo.compute.v1.DeleteClusterRequest
	(*GetClusterRequest)(nil),                                 // 17: org.cudo.compute.v1.GetClusterRequest
	(*ListClustersRequest)(nil),                               // 18: org.cudo.compute.v1.ListClustersRequest
	(*ListClustersResponse)(nil),                              // 19: org.cudo.compute.v1.ListClustersResponse
	(*UpdateClusterRequest)(nil),                              // 20: org.cudo.compute.v1.UpdateClusterRequest
	(*UpdateClusterMachineRequest)(nil),                       // 21: org.cudo.compute.v1.UpdateClusterMachineRequest
	(*RebootClusterMachineRequest)(nil),                       // 22: org.cudo.compute.v1.RebootClusterMachineRequest
	(*RenameClusterMachineRequest)(nil),                       // 23: org.cudo.compute.v1.RenameClusterMachineRequest
	(*DeleteClusterMachineRequest)(nil),                       // 24: org.cudo.compute.v1.DeleteClusterMachineRequest
	(*ListMachineOperatingSystemsResponse_Image)(nil),         // 25: org.cudo.compute.v1.ListMachineOperatingSystemsResponse.Image
	(*ListMachineOperatingSystemsResponse_Image_Package)(nil), // 26: org.cudo.compute.v1.ListMachineOperatingSystemsResponse.Image.Package
	(*MachineInstance)(nil),                                   // 27: org.cudo.compute.v1.MachineInstance
	(*fieldmaskpb.FieldMask)(nil),                             // 28: google.protobuf.FieldMask
	(*MachineType)(nil),                                       // 29: org.cudo.compute.v1.MachineType
	(*Cluster)(nil),                                           // 30: org.cudo.compute.v1.Cluster
	(*ClusterMachine)(nil),                                    // 31: org.cudo.compute.v1.ClusterMachine
	(*ListClusterMachineTypesRequest)(nil),                    // 32: org.cudo.compute.v1.ListClusterMachineTypesRequest
	(*GetClusterMachineTypeRequest)(nil),                      // 33: org.cudo.compute.v1.GetClusterMachineTypeRequest
	(*emptypb.Empty)(nil),                                     // 34: google.protobuf.Empty
	(*ListClusterMachineTypesResponse)(nil),                   // 35: org.cudo.compute.v1.ListClusterMachineTypesResponse
	(*GetClusterMachineTypeResponse)(nil),                     // 36: org.cudo.compute.v1.GetClusterMachineTypeResponse
}
var file_svc_compute_baremetal_baremetal_svc_proto_depIdxs = []int32{
	27, // 0: org.cudo.compute.v1.CreateMachineInstanceRequest.machine_instance:type_name -> org.cudo.compute.v1.MachineInstance
	27, // 1: org.cudo.compute.v1.ListMachineInstancesResponse.machine_instances:type_name -> org.cudo.compute.v1.MachineInstance
	27, // 2: org.cudo.compute.v1.UpdateMachineInstanceRequest.machine_instance:type_name -> org.cudo.compute.v1.MachineInstance
	28, // 3: org.cudo.compute.v1.UpdateMachineInstanceRequest.update_mask:type_name -> google.protobuf.FieldMask
	29, // 4: org.cudo.compute.v1.ListMachineTypesResponse.machine_types:type_name -> org.cudo.compute.v1.MachineType
	25, // 5: org.cudo.compute.v1.ListMachineOperatingSystemsResponse.images:type_name -> org.cudo.compute.v1.ListMachineOperatingSystemsResponse.Image
	30, // 6: org.cudo.compute.v1.CreateClusterRequest.cluster:type_name -> org.cudo.compute.v1.Cluster
	30, // 7: org.cudo.compute.v1.ListClustersResponse.clusters:type_name -> org.cudo.compute.v1.Cluster
	30, // 8: org.cudo.compute.v1.UpdateClusterRequest.cluster:type_name -> org.cudo.compute.v1.Cluster
	28, // 9: org.cudo.compute.v1.UpdateClusterRequest.update_mask:type_name -> google.protobuf.FieldMask
	31, // 10: org.cudo.compute.v1.UpdateClusterMachineRequest.cluster_machine:type_name -> org.cudo.compute.v1.ClusterMachine
	28, // 11: org.cudo.compute.v1.UpdateClusterMachineRequest.update_mask:type_name -> google.protobuf.FieldMask
	26, // 12: org.cudo.compute.v1.ListMachineOperatingSystemsResponse.Image.installed_packages:type_name -> org.cudo.compute.v1.ListMachineOperatingSystemsResponse.Image.Package
	0,  // 13: org.cudo.compute.v1.BareMetalService.CreateMachineInstance:input_type -> org.cudo.compute.v1.CreateMachineInstanceRequest
	1,  // 14: org.cudo.compute.v1.BareMetalService.DeleteMachineInstance:input_type -> org.cudo.compute.v1.DeleteMachineInstanceRequest
	2,  // 15: org.cudo.compute.v1.BareMetalService.GetMachineInstance:input_type -> org.cudo.compute.v1.GetMachineInstanceRequest
	3,  // 16: org.cudo.compute.v1.BareMetalService.ListMachineInstances:input_type -> org.cudo.compute.v1.ListMachineInstancesRequest
	5,  // 17: org.cudo.compute.v1.BareMetalService.UpdateMachineInstance:input_type -> org.cudo.compute.v1.UpdateMachineInstanceRequest
	10, // 18: org.cudo.compute.v1.BareMetalService.PowerOffMachineInstance:input_type -> org.cudo.compute.v1.PowerOffMachineInstanceRequest
	9,  // 19: org.cudo.compute.v1.BareMetalService.PowerOnMachineInstance:input_type -> org.cudo.compute.v1.PowerOnMachineInstanceRequest
	6,  // 20: org.cudo.compute.v1.BareMetalService.DeployMachineInstance:input_type -> org.cudo.compute.v1.DeployMachineInstanceRequest
	7,  // 21: org.cudo.compute.v1.BareMetalService.UndeployMachineInstance:input_type -> org.cudo.compute.v1.UndeployMachineInstanceRequest
	8,  // 22: org.cudo.compute.v1.BareMetalService.EraseMachineInstance:input_type -> org.cudo.compute.v1.EraseMachineInstanceRequest
	13, // 23: org.cudo.compute.v1.BareMetalService.ListMachineOperatingSystems:input_type -> org.cudo.compute.v1.ListMachineOperatingSystemsRequest
	11, // 24: org.cudo.compute.v1.BareMetalService.ListMachineTypes:input_type -> org.cudo.compute.v1.ListMachineTypesRequest
	32, // 25: org.cudo.compute.v1.BareMetalService.ListClusterMachineTypes:input_type -> org.cudo.compute.v1.ListClusterMachineTypesRequest
	33, // 26: org.cudo.compute.v1.BareMetalService.GetClusterMachineType:input_type -> org.cudo.compute.v1.GetClusterMachineTypeRequest
	15, // 27: org.cudo.compute.v1.BareMetalService.CreateCluster:input_type -> org.cudo.compute.v1.CreateClusterRequest
	16, // 28: org.cudo.compute.v1.BareMetalService.DeleteCluster:input_type -> org.cudo.compute.v1.DeleteClusterRequest
	17, // 29: org.cudo.compute.v1.BareMetalService.GetCluster:input_type -> org.cudo.compute.v1.GetClusterRequest
	18, // 30: org.cudo.compute.v1.BareMetalService.ListClusters:input_type -> org.cudo.compute.v1.ListClustersRequest
	20, // 31: org.cudo.compute.v1.BareMetalService.UpdateCluster:input_type -> org.cudo.compute.v1.UpdateClusterRequest
	24, // 32: org.cudo.compute.v1.BareMetalService.DeleteClusterMachine:input_type -> org.cudo.compute.v1.DeleteClusterMachineRequest
	22, // 33: org.cudo.compute.v1.BareMetalService.RebootClusterMachine:input_type -> org.cudo.compute.v1.RebootClusterMachineRequest
	23, // 34: org.cudo.compute.v1.BareMetalService.RenameClusterMachine:input_type -> org.cudo.compute.v1.RenameClusterMachineRequest
	21, // 35: org.cudo.compute.v1.BareMetalService.UpdateClusterMachine:input_type -> org.cudo.compute.v1.UpdateClusterMachineRequest
	27, // 36: org.cudo.compute.v1.BareMetalService.CreateMachineInstance:output_type -> org.cudo.compute.v1.MachineInstance
	34, // 37: org.cudo.compute.v1.BareMetalService.DeleteMachineInstance:output_type -> google.protobuf.Empty
	27, // 38: org.cudo.compute.v1.BareMetalService.GetMachineInstance:output_type -> org.cudo.compute.v1.MachineInstance
	4,  // 39: org.cudo.compute.v1.BareMetalService.ListMachineInstances:output_type -> org.cudo.compute.v1.ListMachineInstancesResponse
	27, // 40: org.cudo.compute.v1.BareMetalService.UpdateMachineInstance:output_type -> org.cudo.compute.v1.MachineInstance
	34, // 41: org.cudo.compute.v1.BareMetalService.PowerOffMachineInstance:output_type -> google.protobuf.Empty
	34, // 42: org.cudo.compute.v1.BareMetalService.PowerOnMachineInstance:output_type -> google.protobuf.Empty
	34, // 43: org.cudo.compute.v1.BareMetalService.DeployMachineInstance:output_type -> google.protobuf.Empty
	34, // 44: org.cudo.compute.v1.BareMetalService.UndeployMachineInstance:output_type -> google.protobuf.Empty
	34, // 45: org.cudo.compute.v1.BareMetalService.EraseMachineInstance:output_type -> google.protobuf.Empty
	14, // 46: org.cudo.compute.v1.BareMetalService.ListMachineOperatingSystems:output_type -> org.cudo.compute.v1.ListMachineOperatingSystemsResponse
	12, // 47: org.cudo.compute.v1.BareMetalService.ListMachineTypes:output_type -> org.cudo.compute.v1.ListMachineTypesResponse
	35, // 48: org.cudo.compute.v1.BareMetalService.ListClusterMachineTypes:output_type -> org.cudo.compute.v1.ListClusterMachineTypesResponse
	36, // 49: org.cudo.compute.v1.BareMetalService.GetClusterMachineType:output_type -> org.cudo.compute.v1.GetClusterMachineTypeResponse
	30, // 50: org.cudo.compute.v1.BareMetalService.CreateCluster:output_type -> org.cudo.compute.v1.Cluster
	34, // 51: org.cudo.compute.v1.BareMetalService.DeleteCluster:output_type -> google.protobuf.Empty
	30, // 52: org.cudo.compute.v1.BareMetalService.GetCluster:output_type -> org.cudo.compute.v1.Cluster
	19, // 53: org.cudo.compute.v1.BareMetalService.ListClusters:output_type -> org.cudo.compute.v1.ListClustersResponse
	30, // 54: org.cudo.compute.v1.BareMetalService.UpdateCluster:output_type -> org.cudo.compute.v1.Cluster
	34, // 55: org.cudo.compute.v1.BareMetalService.DeleteClusterMachine:output_type -> google.protobuf.Empty
	34, // 56: org.cudo.compute.v1.BareMetalService.RebootClusterMachine:output_type -> google.protobuf.Empty
	34, // 57: org.cudo.compute.v1.BareMetalService.RenameClusterMachine:output_type -> google.protobuf.Empty
	31, // 58: org.cudo.compute.v1.BareMetalService.UpdateClusterMachine:output_type -> org.cudo.compute.v1.ClusterMachine
	36, // [36:59] is the sub-list for method output_type
	13, // [13:36] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_svc_compute_baremetal_baremetal_svc_proto_init() }
func file_svc_compute_baremetal_baremetal_svc_proto_init() {
	if File_svc_compute_baremetal_baremetal_svc_proto != nil {
		return
	}
	file_svc_compute_baremetal_baremetal_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svc_compute_baremetal_baremetal_svc_proto_rawDesc), len(file_svc_compute_baremetal_baremetal_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svc_compute_baremetal_baremetal_svc_proto_goTypes,
		DependencyIndexes: file_svc_compute_baremetal_baremetal_svc_proto_depIdxs,
		MessageInfos:      file_svc_compute_baremetal_baremetal_svc_proto_msgTypes,
	}.Build()
	File_svc_compute_baremetal_baremetal_svc_proto = out.File
	file_svc_compute_baremetal_baremetal_svc_proto_goTypes = nil
	file_svc_compute_baremetal_baremetal_svc_proto_depIdxs = nil
}
