// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// GetBillingAccountSetupIntentReader is a Reader for the GetBillingAccountSetupIntent structure.
type GetBillingAccountSetupIntentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBillingAccountSetupIntentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBillingAccountSetupIntentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetBillingAccountSetupIntentDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetBillingAccountSetupIntentOK creates a GetBillingAccountSetupIntentOK with default headers values
func NewGetBillingAccountSetupIntentOK() *GetBillingAccountSetupIntentOK {
	return &GetBillingAccountSetupIntentOK{}
}

/*
GetBillingAccountSetupIntentOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetBillingAccountSetupIntentOK struct {
	Payload *models.BillingAccountSetupIntent
}

// IsSuccess returns true when this get billing account setup intent o k response has a 2xx status code
func (o *GetBillingAccountSetupIntentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get billing account setup intent o k response has a 3xx status code
func (o *GetBillingAccountSetupIntentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get billing account setup intent o k response has a 4xx status code
func (o *GetBillingAccountSetupIntentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get billing account setup intent o k response has a 5xx status code
func (o *GetBillingAccountSetupIntentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get billing account setup intent o k response a status code equal to that given
func (o *GetBillingAccountSetupIntentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get billing account setup intent o k response
func (o *GetBillingAccountSetupIntentOK) Code() int {
	return 200
}

func (o *GetBillingAccountSetupIntentOK) Error() string {
	return fmt.Sprintf("[GET /v1/billing-accounts/{id}/setup-intent][%d] getBillingAccountSetupIntentOK  %+v", 200, o.Payload)
}

func (o *GetBillingAccountSetupIntentOK) String() string {
	return fmt.Sprintf("[GET /v1/billing-accounts/{id}/setup-intent][%d] getBillingAccountSetupIntentOK  %+v", 200, o.Payload)
}

func (o *GetBillingAccountSetupIntentOK) GetPayload() *models.BillingAccountSetupIntent {
	return o.Payload
}

func (o *GetBillingAccountSetupIntentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BillingAccountSetupIntent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBillingAccountSetupIntentDefault creates a GetBillingAccountSetupIntentDefault with default headers values
func NewGetBillingAccountSetupIntentDefault(code int) *GetBillingAccountSetupIntentDefault {
	return &GetBillingAccountSetupIntentDefault{
		_statusCode: code,
	}
}

/*
GetBillingAccountSetupIntentDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetBillingAccountSetupIntentDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this get billing account setup intent default response has a 2xx status code
func (o *GetBillingAccountSetupIntentDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get billing account setup intent default response has a 3xx status code
func (o *GetBillingAccountSetupIntentDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get billing account setup intent default response has a 4xx status code
func (o *GetBillingAccountSetupIntentDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get billing account setup intent default response has a 5xx status code
func (o *GetBillingAccountSetupIntentDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get billing account setup intent default response a status code equal to that given
func (o *GetBillingAccountSetupIntentDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get billing account setup intent default response
func (o *GetBillingAccountSetupIntentDefault) Code() int {
	return o._statusCode
}

func (o *GetBillingAccountSetupIntentDefault) Error() string {
	return fmt.Sprintf("[GET /v1/billing-accounts/{id}/setup-intent][%d] GetBillingAccountSetupIntent default  %+v", o._statusCode, o.Payload)
}

func (o *GetBillingAccountSetupIntentDefault) String() string {
	return fmt.Sprintf("[GET /v1/billing-accounts/{id}/setup-intent][%d] GetBillingAccountSetupIntent default  %+v", o._statusCode, o.Payload)
}

func (o *GetBillingAccountSetupIntentDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *GetBillingAccountSetupIntentDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
