// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// GetBillingAccountReader is a Reader for the GetBillingAccount structure.
type GetBillingAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBillingAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBillingAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetBillingAccountDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetBillingAccountOK creates a GetBillingAccountOK with default headers values
func NewGetBillingAccountOK() *GetBillingAccountOK {
	return &GetBillingAccountOK{}
}

/*
GetBillingAccountOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetBillingAccountOK struct {
	Payload *models.BillingAccount
}

// IsSuccess returns true when this get billing account o k response has a 2xx status code
func (o *GetBillingAccountOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get billing account o k response has a 3xx status code
func (o *GetBillingAccountOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get billing account o k response has a 4xx status code
func (o *GetBillingAccountOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get billing account o k response has a 5xx status code
func (o *GetBillingAccountOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get billing account o k response a status code equal to that given
func (o *GetBillingAccountOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get billing account o k response
func (o *GetBillingAccountOK) Code() int {
	return 200
}

func (o *GetBillingAccountOK) Error() string {
	return fmt.Sprintf("[GET /v1/billing-accounts/{id}][%d] getBillingAccountOK  %+v", 200, o.Payload)
}

func (o *GetBillingAccountOK) String() string {
	return fmt.Sprintf("[GET /v1/billing-accounts/{id}][%d] getBillingAccountOK  %+v", 200, o.Payload)
}

func (o *GetBillingAccountOK) GetPayload() *models.BillingAccount {
	return o.Payload
}

func (o *GetBillingAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BillingAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBillingAccountDefault creates a GetBillingAccountDefault with default headers values
func NewGetBillingAccountDefault(code int) *GetBillingAccountDefault {
	return &GetBillingAccountDefault{
		_statusCode: code,
	}
}

/*
GetBillingAccountDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetBillingAccountDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this get billing account default response has a 2xx status code
func (o *GetBillingAccountDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get billing account default response has a 3xx status code
func (o *GetBillingAccountDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get billing account default response has a 4xx status code
func (o *GetBillingAccountDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get billing account default response has a 5xx status code
func (o *GetBillingAccountDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get billing account default response a status code equal to that given
func (o *GetBillingAccountDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get billing account default response
func (o *GetBillingAccountDefault) Code() int {
	return o._statusCode
}

func (o *GetBillingAccountDefault) Error() string {
	return fmt.Sprintf("[GET /v1/billing-accounts/{id}][%d] GetBillingAccount default  %+v", o._statusCode, o.Payload)
}

func (o *GetBillingAccountDefault) String() string {
	return fmt.Sprintf("[GET /v1/billing-accounts/{id}][%d] GetBillingAccount default  %+v", o._statusCode, o.Payload)
}

func (o *GetBillingAccountDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *GetBillingAccountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
