// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBillingAccountSetupIntentParams creates a new GetBillingAccountSetupIntentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBillingAccountSetupIntentParams() *GetBillingAccountSetupIntentParams {
	return &GetBillingAccountSetupIntentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBillingAccountSetupIntentParamsWithTimeout creates a new GetBillingAccountSetupIntentParams object
// with the ability to set a timeout on a request.
func NewGetBillingAccountSetupIntentParamsWithTimeout(timeout time.Duration) *GetBillingAccountSetupIntentParams {
	return &GetBillingAccountSetupIntentParams{
		timeout: timeout,
	}
}

// NewGetBillingAccountSetupIntentParamsWithContext creates a new GetBillingAccountSetupIntentParams object
// with the ability to set a context for a request.
func NewGetBillingAccountSetupIntentParamsWithContext(ctx context.Context) *GetBillingAccountSetupIntentParams {
	return &GetBillingAccountSetupIntentParams{
		Context: ctx,
	}
}

// NewGetBillingAccountSetupIntentParamsWithHTTPClient creates a new GetBillingAccountSetupIntentParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBillingAccountSetupIntentParamsWithHTTPClient(client *http.Client) *GetBillingAccountSetupIntentParams {
	return &GetBillingAccountSetupIntentParams{
		HTTPClient: client,
	}
}

/*
GetBillingAccountSetupIntentParams contains all the parameters to send to the API endpoint

	for the get billing account setup intent operation.

	Typically these are written to a http.Request.
*/
type GetBillingAccountSetupIntentParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get billing account setup intent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBillingAccountSetupIntentParams) WithDefaults() *GetBillingAccountSetupIntentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get billing account setup intent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBillingAccountSetupIntentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get billing account setup intent params
func (o *GetBillingAccountSetupIntentParams) WithTimeout(timeout time.Duration) *GetBillingAccountSetupIntentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get billing account setup intent params
func (o *GetBillingAccountSetupIntentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get billing account setup intent params
func (o *GetBillingAccountSetupIntentParams) WithContext(ctx context.Context) *GetBillingAccountSetupIntentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get billing account setup intent params
func (o *GetBillingAccountSetupIntentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get billing account setup intent params
func (o *GetBillingAccountSetupIntentParams) WithHTTPClient(client *http.Client) *GetBillingAccountSetupIntentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get billing account setup intent params
func (o *GetBillingAccountSetupIntentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get billing account setup intent params
func (o *GetBillingAccountSetupIntentParams) WithID(id string) *GetBillingAccountSetupIntentParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get billing account setup intent params
func (o *GetBillingAccountSetupIntentParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetBillingAccountSetupIntentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
