// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoveBillingAccountPaymentMethodParams creates a new RemoveBillingAccountPaymentMethodParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveBillingAccountPaymentMethodParams() *RemoveBillingAccountPaymentMethodParams {
	return &RemoveBillingAccountPaymentMethodParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveBillingAccountPaymentMethodParamsWithTimeout creates a new RemoveBillingAccountPaymentMethodParams object
// with the ability to set a timeout on a request.
func NewRemoveBillingAccountPaymentMethodParamsWithTimeout(timeout time.Duration) *RemoveBillingAccountPaymentMethodParams {
	return &RemoveBillingAccountPaymentMethodParams{
		timeout: timeout,
	}
}

// NewRemoveBillingAccountPaymentMethodParamsWithContext creates a new RemoveBillingAccountPaymentMethodParams object
// with the ability to set a context for a request.
func NewRemoveBillingAccountPaymentMethodParamsWithContext(ctx context.Context) *RemoveBillingAccountPaymentMethodParams {
	return &RemoveBillingAccountPaymentMethodParams{
		Context: ctx,
	}
}

// NewRemoveBillingAccountPaymentMethodParamsWithHTTPClient creates a new RemoveBillingAccountPaymentMethodParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveBillingAccountPaymentMethodParamsWithHTTPClient(client *http.Client) *RemoveBillingAccountPaymentMethodParams {
	return &RemoveBillingAccountPaymentMethodParams{
		HTTPClient: client,
	}
}

/*
RemoveBillingAccountPaymentMethodParams contains all the parameters to send to the API endpoint

	for the remove billing account payment method operation.

	Typically these are written to a http.Request.
*/
type RemoveBillingAccountPaymentMethodParams struct {

	// ID.
	ID string

	// PaymentMethodID.
	PaymentMethodID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove billing account payment method params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveBillingAccountPaymentMethodParams) WithDefaults() *RemoveBillingAccountPaymentMethodParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove billing account payment method params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveBillingAccountPaymentMethodParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove billing account payment method params
func (o *RemoveBillingAccountPaymentMethodParams) WithTimeout(timeout time.Duration) *RemoveBillingAccountPaymentMethodParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove billing account payment method params
func (o *RemoveBillingAccountPaymentMethodParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove billing account payment method params
func (o *RemoveBillingAccountPaymentMethodParams) WithContext(ctx context.Context) *RemoveBillingAccountPaymentMethodParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove billing account payment method params
func (o *RemoveBillingAccountPaymentMethodParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove billing account payment method params
func (o *RemoveBillingAccountPaymentMethodParams) WithHTTPClient(client *http.Client) *RemoveBillingAccountPaymentMethodParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove billing account payment method params
func (o *RemoveBillingAccountPaymentMethodParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the remove billing account payment method params
func (o *RemoveBillingAccountPaymentMethodParams) WithID(id string) *RemoveBillingAccountPaymentMethodParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the remove billing account payment method params
func (o *RemoveBillingAccountPaymentMethodParams) SetID(id string) {
	o.ID = id
}

// WithPaymentMethodID adds the paymentMethodID to the remove billing account payment method params
func (o *RemoveBillingAccountPaymentMethodParams) WithPaymentMethodID(paymentMethodID string) *RemoveBillingAccountPaymentMethodParams {
	o.SetPaymentMethodID(paymentMethodID)
	return o
}

// SetPaymentMethodID adds the paymentMethodId to the remove billing account payment method params
func (o *RemoveBillingAccountPaymentMethodParams) SetPaymentMethodID(paymentMethodID string) {
	o.PaymentMethodID = paymentMethodID
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveBillingAccountPaymentMethodParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param paymentMethodId
	if err := r.SetPathParam("paymentMethodId", o.PaymentMethodID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
