// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetBillingAccountDefaultPaymentMethodParams creates a new SetBillingAccountDefaultPaymentMethodParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetBillingAccountDefaultPaymentMethodParams() *SetBillingAccountDefaultPaymentMethodParams {
	return &SetBillingAccountDefaultPaymentMethodParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetBillingAccountDefaultPaymentMethodParamsWithTimeout creates a new SetBillingAccountDefaultPaymentMethodParams object
// with the ability to set a timeout on a request.
func NewSetBillingAccountDefaultPaymentMethodParamsWithTimeout(timeout time.Duration) *SetBillingAccountDefaultPaymentMethodParams {
	return &SetBillingAccountDefaultPaymentMethodParams{
		timeout: timeout,
	}
}

// NewSetBillingAccountDefaultPaymentMethodParamsWithContext creates a new SetBillingAccountDefaultPaymentMethodParams object
// with the ability to set a context for a request.
func NewSetBillingAccountDefaultPaymentMethodParamsWithContext(ctx context.Context) *SetBillingAccountDefaultPaymentMethodParams {
	return &SetBillingAccountDefaultPaymentMethodParams{
		Context: ctx,
	}
}

// NewSetBillingAccountDefaultPaymentMethodParamsWithHTTPClient creates a new SetBillingAccountDefaultPaymentMethodParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetBillingAccountDefaultPaymentMethodParamsWithHTTPClient(client *http.Client) *SetBillingAccountDefaultPaymentMethodParams {
	return &SetBillingAccountDefaultPaymentMethodParams{
		HTTPClient: client,
	}
}

/*
SetBillingAccountDefaultPaymentMethodParams contains all the parameters to send to the API endpoint

	for the set billing account default payment method operation.

	Typically these are written to a http.Request.
*/
type SetBillingAccountDefaultPaymentMethodParams struct {

	// ID.
	ID string

	// PaymentMethodID.
	PaymentMethodID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set billing account default payment method params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetBillingAccountDefaultPaymentMethodParams) WithDefaults() *SetBillingAccountDefaultPaymentMethodParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set billing account default payment method params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetBillingAccountDefaultPaymentMethodParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set billing account default payment method params
func (o *SetBillingAccountDefaultPaymentMethodParams) WithTimeout(timeout time.Duration) *SetBillingAccountDefaultPaymentMethodParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set billing account default payment method params
func (o *SetBillingAccountDefaultPaymentMethodParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set billing account default payment method params
func (o *SetBillingAccountDefaultPaymentMethodParams) WithContext(ctx context.Context) *SetBillingAccountDefaultPaymentMethodParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set billing account default payment method params
func (o *SetBillingAccountDefaultPaymentMethodParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set billing account default payment method params
func (o *SetBillingAccountDefaultPaymentMethodParams) WithHTTPClient(client *http.Client) *SetBillingAccountDefaultPaymentMethodParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set billing account default payment method params
func (o *SetBillingAccountDefaultPaymentMethodParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the set billing account default payment method params
func (o *SetBillingAccountDefaultPaymentMethodParams) WithID(id string) *SetBillingAccountDefaultPaymentMethodParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the set billing account default payment method params
func (o *SetBillingAccountDefaultPaymentMethodParams) SetID(id string) {
	o.ID = id
}

// WithPaymentMethodID adds the paymentMethodID to the set billing account default payment method params
func (o *SetBillingAccountDefaultPaymentMethodParams) WithPaymentMethodID(paymentMethodID string) *SetBillingAccountDefaultPaymentMethodParams {
	o.SetPaymentMethodID(paymentMethodID)
	return o
}

// SetPaymentMethodID adds the paymentMethodId to the set billing account default payment method params
func (o *SetBillingAccountDefaultPaymentMethodParams) SetPaymentMethodID(paymentMethodID string) {
	o.PaymentMethodID = paymentMethodID
}

// WriteToRequest writes these params to a swagger request
func (o *SetBillingAccountDefaultPaymentMethodParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param paymentMethodId
	if err := r.SetPathParam("paymentMethodId", o.PaymentMethodID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
