// Code generated by go-swagger; DO NOT EDIT.

package machine_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// GetMachineTypeReader is a Reader for the GetMachineType structure.
type GetMachineTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMachineTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMachineTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetMachineTypeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMachineTypeOK creates a GetMachineTypeOK with default headers values
func NewGetMachineTypeOK() *GetMachineTypeOK {
	return &GetMachineTypeOK{}
}

/*
GetMachineTypeOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetMachineTypeOK struct {
	Payload *models.GetMachineTypeResponse
}

// IsSuccess returns true when this get machine type o k response has a 2xx status code
func (o *GetMachineTypeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get machine type o k response has a 3xx status code
func (o *GetMachineTypeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get machine type o k response has a 4xx status code
func (o *GetMachineTypeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get machine type o k response has a 5xx status code
func (o *GetMachineTypeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get machine type o k response a status code equal to that given
func (o *GetMachineTypeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get machine type o k response
func (o *GetMachineTypeOK) Code() int {
	return 200
}

func (o *GetMachineTypeOK) Error() string {
	return fmt.Sprintf("[GET /v1/data-centers/{dataCenterId}/machine-types/{machineType}][%d] getMachineTypeOK  %+v", 200, o.Payload)
}

func (o *GetMachineTypeOK) String() string {
	return fmt.Sprintf("[GET /v1/data-centers/{dataCenterId}/machine-types/{machineType}][%d] getMachineTypeOK  %+v", 200, o.Payload)
}

func (o *GetMachineTypeOK) GetPayload() *models.GetMachineTypeResponse {
	return o.Payload
}

func (o *GetMachineTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetMachineTypeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMachineTypeDefault creates a GetMachineTypeDefault with default headers values
func NewGetMachineTypeDefault(code int) *GetMachineTypeDefault {
	return &GetMachineTypeDefault{
		_statusCode: code,
	}
}

/*
GetMachineTypeDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetMachineTypeDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this get machine type default response has a 2xx status code
func (o *GetMachineTypeDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get machine type default response has a 3xx status code
func (o *GetMachineTypeDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get machine type default response has a 4xx status code
func (o *GetMachineTypeDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get machine type default response has a 5xx status code
func (o *GetMachineTypeDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get machine type default response a status code equal to that given
func (o *GetMachineTypeDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get machine type default response
func (o *GetMachineTypeDefault) Code() int {
	return o._statusCode
}

func (o *GetMachineTypeDefault) Error() string {
	return fmt.Sprintf("[GET /v1/data-centers/{dataCenterId}/machine-types/{machineType}][%d] GetMachineType default  %+v", o._statusCode, o.Payload)
}

func (o *GetMachineTypeDefault) String() string {
	return fmt.Sprintf("[GET /v1/data-centers/{dataCenterId}/machine-types/{machineType}][%d] GetMachineType default  %+v", o._statusCode, o.Payload)
}

func (o *GetMachineTypeDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *GetMachineTypeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
