// Code generated by go-swagger; DO NOT EDIT.

package data_centers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// NewCreateDataCenterParams creates a new CreateDataCenterParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateDataCenterParams() *CreateDataCenterParams {
	return &CreateDataCenterParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDataCenterParamsWithTimeout creates a new CreateDataCenterParams object
// with the ability to set a timeout on a request.
func NewCreateDataCenterParamsWithTimeout(timeout time.Duration) *CreateDataCenterParams {
	return &CreateDataCenterParams{
		timeout: timeout,
	}
}

// NewCreateDataCenterParamsWithContext creates a new CreateDataCenterParams object
// with the ability to set a context for a request.
func NewCreateDataCenterParamsWithContext(ctx context.Context) *CreateDataCenterParams {
	return &CreateDataCenterParams{
		Context: ctx,
	}
}

// NewCreateDataCenterParamsWithHTTPClient creates a new CreateDataCenterParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateDataCenterParamsWithHTTPClient(client *http.Client) *CreateDataCenterParams {
	return &CreateDataCenterParams{
		HTTPClient: client,
	}
}

/*
CreateDataCenterParams contains all the parameters to send to the API endpoint

	for the create data center operation.

	Typically these are written to a http.Request.
*/
type CreateDataCenterParams struct {

	// DataCenter.
	DataCenter *models.V1DataCenter

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create data center params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDataCenterParams) WithDefaults() *CreateDataCenterParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create data center params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDataCenterParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create data center params
func (o *CreateDataCenterParams) WithTimeout(timeout time.Duration) *CreateDataCenterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create data center params
func (o *CreateDataCenterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create data center params
func (o *CreateDataCenterParams) WithContext(ctx context.Context) *CreateDataCenterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create data center params
func (o *CreateDataCenterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create data center params
func (o *CreateDataCenterParams) WithHTTPClient(client *http.Client) *CreateDataCenterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create data center params
func (o *CreateDataCenterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDataCenter adds the dataCenter to the create data center params
func (o *CreateDataCenterParams) WithDataCenter(dataCenter *models.V1DataCenter) *CreateDataCenterParams {
	o.SetDataCenter(dataCenter)
	return o
}

// SetDataCenter adds the dataCenter to the create data center params
func (o *CreateDataCenterParams) SetDataCenter(dataCenter *models.V1DataCenter) {
	o.DataCenter = dataCenter
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDataCenterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.DataCenter != nil {
		if err := r.SetBodyParam(o.DataCenter); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
