// Code generated by go-swagger; DO NOT EDIT.

package data_centers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// DeleteDataCenterReader is a Reader for the DeleteDataCenter structure.
type DeleteDataCenterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDataCenterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteDataCenterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteDataCenterDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteDataCenterOK creates a DeleteDataCenterOK with default headers values
func NewDeleteDataCenterOK() *DeleteDataCenterOK {
	return &DeleteDataCenterOK{}
}

/*
DeleteDataCenterOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteDataCenterOK struct {
	Payload interface{}
}

// IsSuccess returns true when this delete data center o k response has a 2xx status code
func (o *DeleteDataCenterOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete data center o k response has a 3xx status code
func (o *DeleteDataCenterOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete data center o k response has a 4xx status code
func (o *DeleteDataCenterOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete data center o k response has a 5xx status code
func (o *DeleteDataCenterOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete data center o k response a status code equal to that given
func (o *DeleteDataCenterOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete data center o k response
func (o *DeleteDataCenterOK) Code() int {
	return 200
}

func (o *DeleteDataCenterOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/data-centers/{id}][%d] deleteDataCenterOK  %+v", 200, o.Payload)
}

func (o *DeleteDataCenterOK) String() string {
	return fmt.Sprintf("[DELETE /v1/data-centers/{id}][%d] deleteDataCenterOK  %+v", 200, o.Payload)
}

func (o *DeleteDataCenterOK) GetPayload() interface{} {
	return o.Payload
}

func (o *DeleteDataCenterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDataCenterDefault creates a DeleteDataCenterDefault with default headers values
func NewDeleteDataCenterDefault(code int) *DeleteDataCenterDefault {
	return &DeleteDataCenterDefault{
		_statusCode: code,
	}
}

/*
DeleteDataCenterDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DeleteDataCenterDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this delete data center default response has a 2xx status code
func (o *DeleteDataCenterDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete data center default response has a 3xx status code
func (o *DeleteDataCenterDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete data center default response has a 4xx status code
func (o *DeleteDataCenterDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete data center default response has a 5xx status code
func (o *DeleteDataCenterDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete data center default response a status code equal to that given
func (o *DeleteDataCenterDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete data center default response
func (o *DeleteDataCenterDefault) Code() int {
	return o._statusCode
}

func (o *DeleteDataCenterDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/data-centers/{id}][%d] DeleteDataCenter default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteDataCenterDefault) String() string {
	return fmt.Sprintf("[DELETE /v1/data-centers/{id}][%d] DeleteDataCenter default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteDataCenterDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *DeleteDataCenterDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
