// Code generated by go-swagger; DO NOT EDIT.

package data_centers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// GetDataCenterLiveUtilizationReader is a Reader for the GetDataCenterLiveUtilization structure.
type GetDataCenterLiveUtilizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDataCenterLiveUtilizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDataCenterLiveUtilizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetDataCenterLiveUtilizationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDataCenterLiveUtilizationOK creates a GetDataCenterLiveUtilizationOK with default headers values
func NewGetDataCenterLiveUtilizationOK() *GetDataCenterLiveUtilizationOK {
	return &GetDataCenterLiveUtilizationOK{}
}

/*
GetDataCenterLiveUtilizationOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetDataCenterLiveUtilizationOK struct {
	Payload *models.GetDataCenterLiveUtilizationResponse
}

// IsSuccess returns true when this get data center live utilization o k response has a 2xx status code
func (o *GetDataCenterLiveUtilizationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get data center live utilization o k response has a 3xx status code
func (o *GetDataCenterLiveUtilizationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data center live utilization o k response has a 4xx status code
func (o *GetDataCenterLiveUtilizationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get data center live utilization o k response has a 5xx status code
func (o *GetDataCenterLiveUtilizationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get data center live utilization o k response a status code equal to that given
func (o *GetDataCenterLiveUtilizationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get data center live utilization o k response
func (o *GetDataCenterLiveUtilizationOK) Code() int {
	return 200
}

func (o *GetDataCenterLiveUtilizationOK) Error() string {
	return fmt.Sprintf("[GET /v1/data-centers/{id}/live-utilization][%d] getDataCenterLiveUtilizationOK  %+v", 200, o.Payload)
}

func (o *GetDataCenterLiveUtilizationOK) String() string {
	return fmt.Sprintf("[GET /v1/data-centers/{id}/live-utilization][%d] getDataCenterLiveUtilizationOK  %+v", 200, o.Payload)
}

func (o *GetDataCenterLiveUtilizationOK) GetPayload() *models.GetDataCenterLiveUtilizationResponse {
	return o.Payload
}

func (o *GetDataCenterLiveUtilizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetDataCenterLiveUtilizationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataCenterLiveUtilizationDefault creates a GetDataCenterLiveUtilizationDefault with default headers values
func NewGetDataCenterLiveUtilizationDefault(code int) *GetDataCenterLiveUtilizationDefault {
	return &GetDataCenterLiveUtilizationDefault{
		_statusCode: code,
	}
}

/*
GetDataCenterLiveUtilizationDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetDataCenterLiveUtilizationDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this get data center live utilization default response has a 2xx status code
func (o *GetDataCenterLiveUtilizationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get data center live utilization default response has a 3xx status code
func (o *GetDataCenterLiveUtilizationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get data center live utilization default response has a 4xx status code
func (o *GetDataCenterLiveUtilizationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get data center live utilization default response has a 5xx status code
func (o *GetDataCenterLiveUtilizationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get data center live utilization default response a status code equal to that given
func (o *GetDataCenterLiveUtilizationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get data center live utilization default response
func (o *GetDataCenterLiveUtilizationDefault) Code() int {
	return o._statusCode
}

func (o *GetDataCenterLiveUtilizationDefault) Error() string {
	return fmt.Sprintf("[GET /v1/data-centers/{id}/live-utilization][%d] GetDataCenterLiveUtilization default  %+v", o._statusCode, o.Payload)
}

func (o *GetDataCenterLiveUtilizationDefault) String() string {
	return fmt.Sprintf("[GET /v1/data-centers/{id}/live-utilization][%d] GetDataCenterLiveUtilization default  %+v", o._statusCode, o.Payload)
}

func (o *GetDataCenterLiveUtilizationDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *GetDataCenterLiveUtilizationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
