// Code generated by go-swagger; DO NOT EDIT.

package data_centers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDataCenterLiveUtilizationParams creates a new GetDataCenterLiveUtilizationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDataCenterLiveUtilizationParams() *GetDataCenterLiveUtilizationParams {
	return &GetDataCenterLiveUtilizationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDataCenterLiveUtilizationParamsWithTimeout creates a new GetDataCenterLiveUtilizationParams object
// with the ability to set a timeout on a request.
func NewGetDataCenterLiveUtilizationParamsWithTimeout(timeout time.Duration) *GetDataCenterLiveUtilizationParams {
	return &GetDataCenterLiveUtilizationParams{
		timeout: timeout,
	}
}

// NewGetDataCenterLiveUtilizationParamsWithContext creates a new GetDataCenterLiveUtilizationParams object
// with the ability to set a context for a request.
func NewGetDataCenterLiveUtilizationParamsWithContext(ctx context.Context) *GetDataCenterLiveUtilizationParams {
	return &GetDataCenterLiveUtilizationParams{
		Context: ctx,
	}
}

// NewGetDataCenterLiveUtilizationParamsWithHTTPClient creates a new GetDataCenterLiveUtilizationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDataCenterLiveUtilizationParamsWithHTTPClient(client *http.Client) *GetDataCenterLiveUtilizationParams {
	return &GetDataCenterLiveUtilizationParams{
		HTTPClient: client,
	}
}

/*
GetDataCenterLiveUtilizationParams contains all the parameters to send to the API endpoint

	for the get data center live utilization operation.

	Typically these are written to a http.Request.
*/
type GetDataCenterLiveUtilizationParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get data center live utilization params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataCenterLiveUtilizationParams) WithDefaults() *GetDataCenterLiveUtilizationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get data center live utilization params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataCenterLiveUtilizationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get data center live utilization params
func (o *GetDataCenterLiveUtilizationParams) WithTimeout(timeout time.Duration) *GetDataCenterLiveUtilizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get data center live utilization params
func (o *GetDataCenterLiveUtilizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get data center live utilization params
func (o *GetDataCenterLiveUtilizationParams) WithContext(ctx context.Context) *GetDataCenterLiveUtilizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get data center live utilization params
func (o *GetDataCenterLiveUtilizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get data center live utilization params
func (o *GetDataCenterLiveUtilizationParams) WithHTTPClient(client *http.Client) *GetDataCenterLiveUtilizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get data center live utilization params
func (o *GetDataCenterLiveUtilizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get data center live utilization params
func (o *GetDataCenterLiveUtilizationParams) WithID(id string) *GetDataCenterLiveUtilizationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get data center live utilization params
func (o *GetDataCenterLiveUtilizationParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDataCenterLiveUtilizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
