// Code generated by go-swagger; DO NOT EDIT.

package data_centers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDataCenterRevenueByResourceParams creates a new GetDataCenterRevenueByResourceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDataCenterRevenueByResourceParams() *GetDataCenterRevenueByResourceParams {
	return &GetDataCenterRevenueByResourceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDataCenterRevenueByResourceParamsWithTimeout creates a new GetDataCenterRevenueByResourceParams object
// with the ability to set a timeout on a request.
func NewGetDataCenterRevenueByResourceParamsWithTimeout(timeout time.Duration) *GetDataCenterRevenueByResourceParams {
	return &GetDataCenterRevenueByResourceParams{
		timeout: timeout,
	}
}

// NewGetDataCenterRevenueByResourceParamsWithContext creates a new GetDataCenterRevenueByResourceParams object
// with the ability to set a context for a request.
func NewGetDataCenterRevenueByResourceParamsWithContext(ctx context.Context) *GetDataCenterRevenueByResourceParams {
	return &GetDataCenterRevenueByResourceParams{
		Context: ctx,
	}
}

// NewGetDataCenterRevenueByResourceParamsWithHTTPClient creates a new GetDataCenterRevenueByResourceParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDataCenterRevenueByResourceParamsWithHTTPClient(client *http.Client) *GetDataCenterRevenueByResourceParams {
	return &GetDataCenterRevenueByResourceParams{
		HTTPClient: client,
	}
}

/*
GetDataCenterRevenueByResourceParams contains all the parameters to send to the API endpoint

	for the get data center revenue by resource operation.

	Typically these are written to a http.Request.
*/
type GetDataCenterRevenueByResourceParams struct {

	// EndTime.
	//
	// Format: date-time
	EndTime strfmt.DateTime

	// ID.
	ID string

	// StartTime.
	//
	// Format: date-time
	StartTime strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get data center revenue by resource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataCenterRevenueByResourceParams) WithDefaults() *GetDataCenterRevenueByResourceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get data center revenue by resource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataCenterRevenueByResourceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get data center revenue by resource params
func (o *GetDataCenterRevenueByResourceParams) WithTimeout(timeout time.Duration) *GetDataCenterRevenueByResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get data center revenue by resource params
func (o *GetDataCenterRevenueByResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get data center revenue by resource params
func (o *GetDataCenterRevenueByResourceParams) WithContext(ctx context.Context) *GetDataCenterRevenueByResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get data center revenue by resource params
func (o *GetDataCenterRevenueByResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get data center revenue by resource params
func (o *GetDataCenterRevenueByResourceParams) WithHTTPClient(client *http.Client) *GetDataCenterRevenueByResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get data center revenue by resource params
func (o *GetDataCenterRevenueByResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEndTime adds the endTime to the get data center revenue by resource params
func (o *GetDataCenterRevenueByResourceParams) WithEndTime(endTime strfmt.DateTime) *GetDataCenterRevenueByResourceParams {
	o.SetEndTime(endTime)
	return o
}

// SetEndTime adds the endTime to the get data center revenue by resource params
func (o *GetDataCenterRevenueByResourceParams) SetEndTime(endTime strfmt.DateTime) {
	o.EndTime = endTime
}

// WithID adds the id to the get data center revenue by resource params
func (o *GetDataCenterRevenueByResourceParams) WithID(id string) *GetDataCenterRevenueByResourceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get data center revenue by resource params
func (o *GetDataCenterRevenueByResourceParams) SetID(id string) {
	o.ID = id
}

// WithStartTime adds the startTime to the get data center revenue by resource params
func (o *GetDataCenterRevenueByResourceParams) WithStartTime(startTime strfmt.DateTime) *GetDataCenterRevenueByResourceParams {
	o.SetStartTime(startTime)
	return o
}

// SetStartTime adds the startTime to the get data center revenue by resource params
func (o *GetDataCenterRevenueByResourceParams) SetStartTime(startTime strfmt.DateTime) {
	o.StartTime = startTime
}

// WriteToRequest writes these params to a swagger request
func (o *GetDataCenterRevenueByResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param endTime
	qrEndTime := o.EndTime
	qEndTime := qrEndTime.String()
	if qEndTime != "" {

		if err := r.SetQueryParam("endTime", qEndTime); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// query param startTime
	qrStartTime := o.StartTime
	qStartTime := qrStartTime.String()
	if qStartTime != "" {

		if err := r.SetQueryParam("startTime", qStartTime); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
