// Code generated by go-swagger; DO NOT EDIT.

package data_centers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CudoVentures/terraform-provider-cudo/internal/models"
)

// ListDataCentersReader is a Reader for the ListDataCenters structure.
type ListDataCentersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListDataCentersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListDataCentersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListDataCentersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListDataCentersOK creates a ListDataCentersOK with default headers values
func NewListDataCentersOK() *ListDataCentersOK {
	return &ListDataCentersOK{}
}

/*
ListDataCentersOK describes a response with status code 200, with default header values.

A successful response.
*/
type ListDataCentersOK struct {
	Payload *models.ListDataCentersResponse
}

// IsSuccess returns true when this list data centers o k response has a 2xx status code
func (o *ListDataCentersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list data centers o k response has a 3xx status code
func (o *ListDataCentersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list data centers o k response has a 4xx status code
func (o *ListDataCentersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list data centers o k response has a 5xx status code
func (o *ListDataCentersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list data centers o k response a status code equal to that given
func (o *ListDataCentersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list data centers o k response
func (o *ListDataCentersOK) Code() int {
	return 200
}

func (o *ListDataCentersOK) Error() string {
	return fmt.Sprintf("[GET /v1/data-centers][%d] listDataCentersOK  %+v", 200, o.Payload)
}

func (o *ListDataCentersOK) String() string {
	return fmt.Sprintf("[GET /v1/data-centers][%d] listDataCentersOK  %+v", 200, o.Payload)
}

func (o *ListDataCentersOK) GetPayload() *models.ListDataCentersResponse {
	return o.Payload
}

func (o *ListDataCentersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListDataCentersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListDataCentersDefault creates a ListDataCentersDefault with default headers values
func NewListDataCentersDefault(code int) *ListDataCentersDefault {
	return &ListDataCentersDefault{
		_statusCode: code,
	}
}

/*
ListDataCentersDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ListDataCentersDefault struct {
	_statusCode int

	Payload *models.Status
}

// IsSuccess returns true when this list data centers default response has a 2xx status code
func (o *ListDataCentersDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list data centers default response has a 3xx status code
func (o *ListDataCentersDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list data centers default response has a 4xx status code
func (o *ListDataCentersDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list data centers default response has a 5xx status code
func (o *ListDataCentersDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list data centers default response a status code equal to that given
func (o *ListDataCentersDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list data centers default response
func (o *ListDataCentersDefault) Code() int {
	return o._statusCode
}

func (o *ListDataCentersDefault) Error() string {
	return fmt.Sprintf("[GET /v1/data-centers][%d] ListDataCenters default  %+v", o._statusCode, o.Payload)
}

func (o *ListDataCentersDefault) String() string {
	return fmt.Sprintf("[GET /v1/data-centers][%d] ListDataCenters default  %+v", o._statusCode, o.Payload)
}

func (o *ListDataCentersDefault) GetPayload() *models.Status {
	return o.Payload
}

func (o *ListDataCentersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
