// Code generated by go-swagger; DO NOT EDIT.

package data_centers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateDataCenterParams creates a new UpdateDataCenterParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateDataCenterParams() *UpdateDataCenterParams {
	return &UpdateDataCenterParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDataCenterParamsWithTimeout creates a new UpdateDataCenterParams object
// with the ability to set a timeout on a request.
func NewUpdateDataCenterParamsWithTimeout(timeout time.Duration) *UpdateDataCenterParams {
	return &UpdateDataCenterParams{
		timeout: timeout,
	}
}

// NewUpdateDataCenterParamsWithContext creates a new UpdateDataCenterParams object
// with the ability to set a context for a request.
func NewUpdateDataCenterParamsWithContext(ctx context.Context) *UpdateDataCenterParams {
	return &UpdateDataCenterParams{
		Context: ctx,
	}
}

// NewUpdateDataCenterParamsWithHTTPClient creates a new UpdateDataCenterParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateDataCenterParamsWithHTTPClient(client *http.Client) *UpdateDataCenterParams {
	return &UpdateDataCenterParams{
		HTTPClient: client,
	}
}

/*
UpdateDataCenterParams contains all the parameters to send to the API endpoint

	for the update data center operation.

	Typically these are written to a http.Request.
*/
type UpdateDataCenterParams struct {

	// DataCenter.
	DataCenter UpdateDataCenterBody

	// DataCenterID.
	DataCenterID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update data center params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDataCenterParams) WithDefaults() *UpdateDataCenterParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update data center params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDataCenterParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update data center params
func (o *UpdateDataCenterParams) WithTimeout(timeout time.Duration) *UpdateDataCenterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update data center params
func (o *UpdateDataCenterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update data center params
func (o *UpdateDataCenterParams) WithContext(ctx context.Context) *UpdateDataCenterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update data center params
func (o *UpdateDataCenterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update data center params
func (o *UpdateDataCenterParams) WithHTTPClient(client *http.Client) *UpdateDataCenterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update data center params
func (o *UpdateDataCenterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDataCenter adds the dataCenter to the update data center params
func (o *UpdateDataCenterParams) WithDataCenter(dataCenter UpdateDataCenterBody) *UpdateDataCenterParams {
	o.SetDataCenter(dataCenter)
	return o
}

// SetDataCenter adds the dataCenter to the update data center params
func (o *UpdateDataCenterParams) SetDataCenter(dataCenter UpdateDataCenterBody) {
	o.DataCenter = dataCenter
}

// WithDataCenterID adds the dataCenterID to the update data center params
func (o *UpdateDataCenterParams) WithDataCenterID(dataCenterID string) *UpdateDataCenterParams {
	o.SetDataCenterID(dataCenterID)
	return o
}

// SetDataCenterID adds the dataCenterId to the update data center params
func (o *UpdateDataCenterParams) SetDataCenterID(dataCenterID string) {
	o.DataCenterID = dataCenterID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDataCenterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.DataCenter); err != nil {
		return err
	}

	// path param dataCenter.id
	if err := r.SetPathParam("dataCenter.id", o.DataCenterID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
